// Günlük içerik verileri: günün ayeti, tarihte bugün, kız/erkek isimleri.
// Günün öğesi, yılın gününe (dayOfYear) göre deterministik seçilir.

class AyetGunun {
  final String metin;
  final String kaynak;
  const AyetGunun(this.metin, this.kaynak);
}

const List<AyetGunun> kGununAyetleri = [
  AyetGunun('Şüphesiz her zorlukla beraber bir kolaylık vardır.', 'İnşirah 6'),
  AyetGunun('Allah, hiç kimseye gücünün üstünde bir şey yüklemez.', 'Bakara 286'),
  AyetGunun('Beni anın ki ben de sizi anayım.', 'Bakara 152'),
  AyetGunun('Kalpler ancak Allah\'ı anmakla huzur bulur.', 'Ra\'d 28'),
  AyetGunun('Rabbiniz buyurdu ki: Bana dua edin, size cevap vereyim.', 'Mü\'min 60'),
  AyetGunun('Sabredenlere mükâfatları hesapsız ödenecektir.', 'Zümer 10'),
  AyetGunun('Allah sabredenlerle beraberdir.', 'Bakara 153'),
  AyetGunun('Kim Allah\'a güvenirse, O ona yeter.', 'Talâk 3'),
  AyetGunun('Umutsuzluğa düşmeyin; Allah\'ın rahmetinden ancak kâfirler umut keser.', 'Yûsuf 87'),
  AyetGunun('İyilikle kötülük bir olmaz. Sen kötülüğü en güzel şekilde sav.', 'Fussilet 34'),
  AyetGunun('Allah\'ın rahmetinden umut kesmeyin.', 'Zümer 53'),
  AyetGunun('Şükrederseniz, elbette size nimetimi artırırım.', 'İbrâhim 7'),
  AyetGunun('Göklerin ve yerin anahtarları O\'nundur.', 'Zümer 63'),
  AyetGunun('Rabbim! İlmimi artır.', 'Tâhâ 114'),
  AyetGunun('İnsan için ancak çalıştığının karşılığı vardır.', 'Necm 39'),
  AyetGunun('Allah, adaleti, iyiliği ve akrabaya yardımı emreder.', 'Nahl 90'),
  AyetGunun('Birbirinizle iyi geçinin; şüphesiz Allah iyilik edenleri sever.', 'Bakara 195'),
  AyetGunun('Sözün en güzelini söyleyin.', 'İsrâ 53'),
  AyetGunun('Kim bir canı kurtarırsa, bütün insanları kurtarmış gibidir.', 'Mâide 32'),
  AyetGunun('Rabbimiz! Bize dünyada da ahirette de iyilik ver.', 'Bakara 201'),
  AyetGunun('And olsun ki sizi biraz korku, açlık ve mal eksikliğiyle deneriz; sabredenleri müjdele.', 'Bakara 155'),
  AyetGunun('Allah\'a çağıran ve iyi iş yapandan daha güzel sözlü kim olabilir?', 'Fussilet 33'),
  AyetGunun('O, gökten su indirendir.', 'En\'âm 99'),
  AyetGunun('De ki: Ey kendi aleyhlerine aşırı giden kullarım! Allah\'ın rahmetinden ümit kesmeyin.', 'Zümer 53'),
  AyetGunun('Namazı kıl; çünkü namaz hayâsızlıktan ve kötülükten alıkoyar.', 'Ankebût 45'),
  AyetGunun('Allah, temizlenenleri sever.', 'Tevbe 108'),
  AyetGunun('Bize düşen ancak açıkça tebliğdir.', 'Yâsîn 17'),
  AyetGunun('Rabbin, sana verecek ve sen de razı olacaksın.', 'Duhâ 5'),
  AyetGunun('Muhakkak ki Allah her şeye kadirdir.', 'Bakara 20'),
  AyetGunun('İyilik edin; Allah iyilik edenleri sever.', 'Bakara 195'),
];

// Tarihte bugün: 'MM-DD' → dinî/tarihî olay(lar). Miladi tarih esas alınır
// (bilinen sabit tarihler; hicri tabanlı bazıları yaklaşık verilmiştir).
const Map<String, List<String>> kTarihteBugun = {
  '01-01': ['Birçok İslam devletinde yeni yıl vesilesiyle hayır ve dua toplulukları düzenlenirdi.'],
  '01-24': ['1077 — Selçuklu döneminde ilim ve medrese faaliyetleri Anadolu\'da yayılmaya başladı (Nizamiye medreseleri etkisi).'],
  '02-12': ['1554 — Osmanlı âlimi ve şeyhülislam geleneğinde fıkıh çalışmaları güçlendi.'],
  '03-04': ['1193 — Selâhaddin Eyyûbî\'nin vefatı (Kudüs\'ü Haçlılardan geri alan komutan).'],
  '04-06': ['1250 — Mısır\'da Memlûk döneminin başlangıcı; İslam dünyasının Moğol/Haçlı tehdidine karşı direnci.'],
  '05-29': ['1453 — İstanbul\'un Fethi. Sultan II. Mehmed (Fâtih) Konstantinopolis\'i fethetti; Peygamberimizin müjdesine (hadis) mazhar oldu.'],
  '06-08': ['632 — Hz. Muhammed\'in (s.a.v.) vefatı (Rebiülevvel ayına denk gelen dönem, Medine).'],
  '07-04': ['Hicri takvimde çeşitli yıllarda Ramazan ve fetih olaylarına denk gelen bir gündür.'],
  '07-15': ['1099 — Haçlıların Kudüs\'ü işgali; sonraki asırda Selâhaddin tarafından geri alınacaktır.'],
  '08-20': ['1191 — Selâhaddin Eyyûbî döneminde Haçlılarla mücadeleler sürüyordu.'],
  '09-27': ['1529 — Osmanlı\'nın Viyana Kuşatması; İslam ve Osmanlı tarihinde dönüm noktalarından.'],
  '10-13': ['1st asır — İslam\'ın ilk yıllarında tebliğ ve hicret hazırlıkları bu döneme rastlar.'],
  '11-24': ['1071 — Malazgirt Zaferi\'nin ardından Anadolu\'nun İslamlaşma süreci hızlandı.'],
  '12-18': ['1273 — Mevlânâ Celâleddîn-i Rûmî\'nin vefatı (Şeb-i Arûs — "düğün gecesi"), Konya.'],
};

class Isim {
  final String isim;
  final String anlam;
  const Isim(this.isim, this.anlam);
}

const List<Isim> kKizIsimleri = [
  Isim('Âmine', 'Emin, güvenilir, korkusuz; Peygamberimizin annesinin adı.'),
  Isim('Hatice', 'Erken doğan; Peygamberimizin ilk eşi Hz. Hatice.'),
  Isim('Âişe', 'Yaşayan, hayat dolu; Peygamberimizin eşi.'),
  Isim('Fâtıma', 'Sütten kesen; Peygamberimizin kızı.'),
  Isim('Meryem', 'İbadet eden, âbide; Hz. İsa\'nın annesi.'),
  Isim('Zeynep', 'Değerli süs ağacı, güzel kokulu çiçek.'),
  Isim('Rukiye', 'Yükselen, yüce; şifa duası.'),
  Isim('Sümeyye', 'Yüce, adı anılan; İslam\'ın ilk kadın şehidi.'),
  Isim('Esma', 'İsimler; Hz. Ebû Bekir\'in kızı Esma bint Ebû Bekir.'),
  Isim('Havva', 'Yaşam veren; ilk kadın Hz. Havva.'),
  Isim('Sâre', 'Saf, hâlis; Hz. İbrahim\'in eşi.'),
  Isim('Hacer', 'Göç eden; Hz. İsmail\'in annesi.'),
  Isim('Belkıs', 'Sebe melikesi; Hz. Süleyman kıssasında geçer.'),
  Isim('Âsiye', 'İsyan etmeyen, teselli eden; Firavun\'un iman eden eşi.'),
  Isim('Hafsa', 'Yavru aslan; Peygamberimizin eşi Hz. Hafsa.'),
  Isim('Safiye', 'Saf, temiz, seçkin; Peygamberimizin eşi.'),
  Isim('Cüveyriye', 'Küçük kız; Peygamberimizin eşi.'),
  Isim('Reyhan', 'Güzel kokulu fesleğen; cennet kokusu.'),
  Isim('Büşra', 'Müjde, sevindirici haber.'),
  Isim('Kevser', 'Bolluk, cennet ırmağı; Kevser sûresi.'),
  Isim('Sena', 'Övgü, şükür, aydınlık.'),
  Isim('Tûba', 'Ne mutlu; cennet ağacı.'),
  Isim('Sidre', 'Cennette bir ağaç (Sidretü\'l-Müntehâ).'),
  Isim('Nur', 'Işık, aydınlık; Nûr sûresi.'),
  Isim('Hüda', 'Doğru yol, hidayet.'),
  Isim('İkram', 'Ağırlama, cömertlik, ikram etme.'),
  Isim('Berra', 'İyilik eden, hayırlı.'),
  Isim('Merve', 'Mekke\'de kutsal tepe; sa\'y yapılan yer.'),
  Isim('Zemzem', 'Mekke\'deki mübarek su kaynağı.'),
  Isim('İrem', 'Cennet bahçesi, güzel bahçe.'),
  Isim('Elif', 'Alfabenin ilk harfi; dostluk, ülfet.'),
  Isim('Beyza', 'Bembeyaz, tertemiz, parlak.'),
  Isim('Duha', 'Kuşluk vakti; Duhâ sûresi.'),
  Isim('Rahime', 'Merhametli, şefkatli.'),
  Isim('Selma', 'Barış, esenlik içinde olan.'),
  Isim('Şevval', 'Ramazan sonrası ay; bayram ayı.'),
  Isim('Zehra', 'Parlak, nurlu; Hz. Fâtıma\'nın lakabı.'),
  Isim('Kübra', 'En büyük, en yüce.'),
  Isim('Sabire', 'Sabreden, tahammüllü.'),
  Isim('Nazan', 'Nazlı, edalı.'),
  Isim('Firdevs', 'En yüksek cennet.'),
  Isim('Refia', 'Yüce, yüksek, değerli.'),
  Isim('Betül', 'İffetli, temiz; Hz. Meryem ve Hz. Fâtıma\'nın vasfı.'),
  Isim('Nesibe', 'Soylu, asil; ilk kadın sahâbelerden Nesibe Hatun.'),
  Isim('Ümmügülsüm', 'Peygamberimizin kızlarından biri.'),
  Isim('Halime', 'Yumuşak huylu; Peygamberimizin süt annesi Halime.'),
  Isim('Şifa', 'Deva, iyileşme; sahâbe hanım Şifâ bint Abdullah.'),
  Isim('Rana', 'Güzel, göz alıcı.'),
  Isim('Ceylan', 'Zarif, güzel gözlü.'),
  Isim('Lâle', 'Süs çiçeği; Allah lafzını andıran çiçek.'),
  Isim('Aleyna', 'Bizim üzerimize; üstün, yüce.'),
  Isim('Azra', 'Temiz, iffetli, bakire.'),
  Isim('Cemre', 'Kışın havayı, suyu ve toprağı ısıtan sıcaklık.'),
  Isim('Damla', 'Su damlası; küçük ve değerli.'),
  Isim('Defne', 'Zafer sembolü olan yaprağı sürekli yeşil ağaç.'),
  Isim('Dilara', 'Gönül alan, sevgili.'),
  Isim('Ebrar', 'İyiler, hayır sahipleri, dürüstler.'),
  Isim('Ecrin', 'Allah\'ın armağanı, mükâfat.'),
  Isim('Eda', 'Naz, işve, hoş tavır.'),
  Isim('Elvan', 'Renkler, çeşit çeşit.'),
  Isim('Emine', 'Güvenilir, emin, korkusuz.'),
  Isim('Esila', 'Akşam vakti, ikindi sonrası.'),
  Isim('Esra', 'Gece yürüyüşü; İsrâ sûresine izafeten.'),
  Isim('Feyza', 'Bolluk, bereket, feyiz.'),
  Isim('Gamze', 'Yanakta oluşan çukur, tebessüm izi.'),
  Isim('Gülsüm', 'Yuvarlak ve dolgun yüzlü; Peygamber ailesinden isim.'),
  Isim('Hira', 'İlk vahyin geldiği mağara.'),
  Isim('İlayda', 'Su perisi; bereketli su.'),
  Isim('İnci', 'Sedefte oluşan değerli beyaz taş.'),
  Isim('Kadriye', 'Değerli, kıymetli; Kadir gecesine izafeten.'),
  Isim('Kumsal', 'Deniz kenarındaki ince kum.'),
  Isim('Lamia', 'Parlayan, parıldayan.'),
  Isim('Leyla', 'Gece; uzun ve karanlık gece.'),
  Isim('Mavi', 'Gökyüzü ve deniz rengi.'),
  Isim('Melek', 'Nurdan yaratılmış varlık; masum, güzel.'),
  Isim('Melike', 'Kraliçe, hükümdar kadın.'),
  Isim('Mihriban', 'Sevgi dolu, şefkatli.'),
  Isim('Mina', 'Liman; mavi renk; cam gibi parlak.'),
  Isim('Mira', 'Bereketli, huzur veren; hükümdar soyundan.'),
  Isim('Nehir', 'Akarsu, ırmak.'),
  Isim('Nisa', 'Kadınlar; Nisâ sûresine izafeten.'),
  Isim('Öykü', 'Kısa hikâye, anlatı.'),
  Isim('Pınar', 'Kaynak, göze; temiz su çıkan yer.'),
  Isim('Rabia', 'Dördüncü; ünlü âbide Râbiatü\'l-Adeviyye.'),
  Isim('Reyyan', 'Cennette oruç tutanların gireceği kapı.'),
  Isim('Rüya', 'Uykuda görülen düş.'),
  Isim('Sedef', 'İçinde inci oluşan parlak deniz kabuğu.'),
  Isim('Sude', 'Sürülmüş, saf, halis.'),
  Isim('Sultan', 'Hükümdar; güç ve otorite sahibi.'),
  Isim('Sümeyra', 'Küçük buğday tenli; sahâbe hanım adı.'),
  Isim('Şevval', 'Ramazan sonrası hicri ay; bayram ayı.'),
  Isim('Tuana', 'Cennetten gelen, ilahi güzellik.'),
  Isim('Ümmühan', 'Hanımların hanımefendisi.'),
  Isim('Vildan', 'Cennet hizmetçileri; yeni doğanlar.'),
  Isim('Yağmur', 'Gökten inen bereket, rahmet.'),
  Isim('Yasemin', 'Beyaz, güzel kokulu çiçek.'),
  Isim('Yaren', 'Yakın dost, sırdaş.'),
  Isim('Yıldız', 'Gökyüzünde parlayan gök cismi.'),
  Isim('Zahide', 'Dünyaya değer vermeyen, zâhit.'),
  Isim('Zeliha', 'Hz. Yûsuf kıssasında adı geçen kadın.'),
  Isim('Zümra', 'Akıllı, zeki; en iyi, en olgun.'),
  Isim('Adviye', 'Güzel kokulu bitki, şifalı ot.'),
  Isim('Berfin', 'Kar çiçeği, kardelen.'),
  Isim('Berra', 'Anne sütü emen; iyilik eden.'),
  Isim('Bihter', 'En iyi, daha güzel.'),
  Isim('Buğlem', 'Cennette bir meyve; tatlı.'),
  Isim('Cana', 'Candan, sevgili, içten.'),
  Isim('Ceren', 'Ceylan yavrusu; zarif.'),
  Isim('Çağla', 'Olgunlaşmamış taze badem/erik.'),
  Isim('Dilan', 'Gönüller, sevgi.'),
  Isim('Ela', 'Sarıya çalan kahverengi göz rengi.'),
  Isim('Esmanur', 'Güzel isimlerin nuru.'),
  Isim('Fatmanur', 'Fâtıma ile nurun birleşimi.'),
  Isim('Gökçe', 'Mavi, gök rengi; güzel.'),
  Isim('Hafsanur', 'Hafsa ile nurun birleşimi.'),
  Isim('Iraz', 'Mutluluk, saadet, murat.'),
  Isim('İpek', 'İnce, yumuşak ve değerli kumaş.'),
  Isim('Kayra', 'Allah\'ın lütfu, ihsan.'),
  Isim('Lina', 'Yumuşak, ince; hurma dalı.'),
  Isim('Masal', 'Olağanüstü anlatı, düşsel hikâye.'),
  Isim('Miray', 'Ay gibi parlak; hükümdar ay.'),
  Isim('Naz', 'İşve, cilve, nazlanma.'),
  Isim('Nehir', 'Irmak, akarsu.'),
  Isim('Ravza', 'Cennet bahçesi; Peygamber\'in kabri civarı.'),
  Isim('Sıla', 'Kavuşma, memlekete dönüş.'),
  Isim('Talia', 'Talih, baht, yükselen yıldız.'),
  Isim('Vera', 'Takva, haramdan sakınma.'),
  Isim('Zeynure', 'Süs ve nurun birleşimi.'),
];

const List<Isim> kErkekIsimleri = [
  Isim('Muhammed', 'Övülmüş, çokça hamd edilen; Peygamberimizin adı.'),
  Isim('Ahmed', 'En çok öven, övülmeye değer; Peygamberimizin bir diğer adı.'),
  Isim('Mustafa', 'Seçilmiş, ıstıfa edilmiş; Peygamberimizin adı.'),
  Isim('Mahmud', 'Övülen, methedilen.'),
  Isim('Ebubekir', 'Devenin yavrusuna düşkün; ilk halife Hz. Ebû Bekir.'),
  Isim('Ömer', 'Uzun ömürlü, mamur eden; ikinci halife Hz. Ömer.'),
  Isim('Osman', 'Toy kuşunun yavrusu; üçüncü halife Hz. Osman.'),
  Isim('Ali', 'Yüce, yüksek, şerefli; dördüncü halife Hz. Ali.'),
  Isim('Hamza', 'Aslan, heybetli; Peygamberimizin amcası Hz. Hamza.'),
  Isim('Bilal', 'Su, ıslaklık; ilk müezzin Hz. Bilal-i Habeşî.'),
  Isim('Yusuf', 'Allah katsın, artırsın; Hz. Yûsuf.'),
  Isim('İbrahim', 'Merhametli baba; Hz. İbrahim (Halîlullah).'),
  Isim('İsmail', 'Allah işitti; Hz. İsmail.'),
  Isim('Musa', 'Sudan çıkarılan; Hz. Musa (Kelîmullah).'),
  Isim('İsa', 'Rabbin kurtardığı; Hz. İsa.'),
  Isim('Nuh', 'Uzun ömürlü; Hz. Nuh.'),
  Isim('Davud', 'Sevgili, aziz; Hz. Davud.'),
  Isim('Süleyman', 'Selâmet, esenlik; Hz. Süleyman.'),
  Isim('Yakub', 'Takip eden, izinden giden; Hz. Yakub.'),
  Isim('Yunus', 'Ünsiyet eden, cana yakın; Hz. Yunus.'),
  Isim('Zekeriya', 'Allah\'ı çokça anan; Hz. Zekeriya.'),
  Isim('Yahya', 'Yaşayan, diri; Hz. Yahya.'),
  Isim('İdris', 'Çok ders çalışan, ilim ehli; Hz. İdris.'),
  Isim('Salih', 'İyi, dürüst, faydalı; Hz. Salih.'),
  Isim('Harun', 'Yüksek, ulu; Hz. Harun.'),
  Isim('Eyüp', 'Sabrın sembolü; Hz. Eyyûb.'),
  Isim('Talha', 'Bir tür ağaç, muz ağacı; cennetle müjdelenen sahâbe.'),
  Isim('Zübeyir', 'Güçlü, akıllı; cennetle müjdelenen sahâbe.'),
  Isim('Halid', 'Ebedî, kalıcı; komutan Halid bin Velid.'),
  Isim('Sa\'d', 'Mutluluk, uğur; Sa\'d bin Ebî Vakkas.'),
  Isim('Enes', 'Cana yakın, dost; Peygamber hizmetçisi Enes bin Mâlik.'),
  Isim('Muaz', 'Korunan, sığınılan; Muâz bin Cebel.'),
  Isim('Selman', 'Barış içinde; Selmân-ı Fârisî.'),
  Isim('Süheyb', 'Kızıla çalan; Süheyb-i Rûmî.'),
  Isim('Cafer', 'Küçük akarsu; Cafer-i Tayyar.'),
  Isim('Abdullah', 'Allah\'ın kulu; Peygamberimizin babası.'),
  Isim('Abdurrahman', 'Rahmân\'ın kulu.'),
  Isim('Abdulaziz', 'Aziz olan Allah\'ın kulu.'),
  Isim('Hasan', 'Güzel, iyi; Peygamberimizin torunu Hz. Hasan.'),
  Isim('Hüseyin', 'Güzelce, sevimli; Peygamberimizin torunu Hz. Hüseyin.'),
  Isim('Enes', 'Cana yakın, ünsiyet eden.'),
  Isim('Kerem', 'Cömertlik, soyluluk, lütuf.'),
  Isim('Emir', 'Bey, yönetici, komutan.'),
  Isim('Yasin', 'Kur\'an\'da bir sûrenin adı; "Ey insan" hitabı.'),
  Isim('Taha', 'Kur\'an\'da bir sûrenin adı.'),
  Isim('Furkan', 'Hakkı bâtıldan ayıran; Kur\'an\'ın adı.'),
  Isim('Kuddus', 'Her türlü eksiklikten uzak; Allah\'ın ismi.'),
  Isim('Selahaddin', 'Dinin iyiliği; Selâhaddin Eyyûbî.'),
  Isim('Bera', 'Üstün, temiz, hayırlı; sahâbe Berâ bin Âzib.'),
  Isim('Ubeyde', 'Küçük kul; Ebû Ubeyde bin Cerrâh.'),
  Isim('Yiğit', 'Cesur, kahraman, mert.'),
  Isim('Kaan', 'Hükümdar, hakan.'),
  Isim('Poyraz', 'Kuzeydoğudan esen soğuk rüzgâr.'),
  Isim('Aras', 'Doğu Anadolu\'da bir nehir; akıcı.'),
  Isim('Arda', 'Dizi, sıra; ardından gelen, nesil.'),
  Isim('Alp', 'Yiğit, kahraman, cesur.'),
  Isim('Alparslan', 'Yiğit aslan; Selçuklu sultanı.'),
  Isim('Aziz', 'Yüce, değerli, izzetli; Allah\'ın ismi.'),
  Isim('Berat', 'Beraat, aklanma; Berat kandiline izafeten.'),
  Isim('Burak', 'Mirac gecesi Peygamber\'i taşıyan binek; parlak.'),
  Isim('Bora', 'Şiddetli fırtına, kuvvetli rüzgâr.'),
  Isim('Cihan', 'Dünya, âlem, evren.'),
  Isim('Çınar', 'Uzun ömürlü, heybetli ağaç.'),
  Isim('Demir', 'Sağlam, dayanıklı maden.'),
  Isim('Doruk', 'Zirve, en yüksek nokta.'),
  Isim('Ege', 'Koruyucu, sahip; Ege denizi.'),
  Isim('Emir', 'Bey, komutan, yönetici.'),
  Isim('Emirhan', 'Emir ile han; hükümdar.'),
  Isim('Eren', 'Ermiş, olgun, veli.'),
  Isim('Ensar', 'Yardımcılar; Medineli Müslümanlar.'),
  Isim('Eymen', 'Uğurlu, bereketli, sağ taraf.'),
  Isim('Fatih', 'Fetheden, zafer kazanan; Sultan II. Mehmed.'),
  Isim('Ferhat', 'Sevinç, neşe; ünlü aşk kahramanı.'),
  Isim('Göktuğ', 'Gökyüzünün sancağı.'),
  Isim('Hamza', 'Aslan; Peygamber\'in amcası.'),
  Isim('Kağan', 'Hükümdar, kağan, en yüksek unvan.'),
  Isim('Kayra', 'Allah\'ın lütfu, ihsan.'),
  Isim('Kerem', 'Cömertlik, soyluluk, lütuf.'),
  Isim('Kuzey', 'Dört ana yönden biri.'),
  Isim('Mert', 'Yiğit, sözünün eri, güvenilir.'),
  Isim('Metehan', 'Büyük Hun hükümdarı; güçlü lider.'),
  Isim('Miraç', 'Peygamber\'in göğe yükselişi; yükseliş.'),
  Isim('Muhammet', 'Övülmüş; Peygamberimizin adı.'),
  Isim('Ömer', 'Uzun ömürlü; ikinci halife.'),
  Isim('Poyraz', 'Kuzey rüzgârı.'),
  Isim('Rüzgar', 'Esinti, yel.'),
  Isim('Sarp', 'Dik, çetin, geçilmesi zor.'),
  Isim('Selim', 'Sağlam, kusursuz, esenlik içinde.'),
  Isim('Sinan', 'Mızrak ucu; Mimar Sinan.'),
  Isim('Taha', 'Kur\'an\'da bir sûrenin adı.'),
  Isim('Tarık', 'Sabah yıldızı; kapı çalan; Târık sûresi.'),
  Isim('Toprak', 'Bereket, verimlilik, tevazu.'),
  Isim('Tuna', 'Avrupa\'nın büyük nehri; bol, gür.'),
  Isim('Umut', 'Ümit, beklenti, iyimserlik.'),
  Isim('Yaman', 'Güçlü, becerikli, zorlu.'),
  Isim('Yavuz', 'Sert, keskin, yiğit; Yavuz Sultan Selim.'),
  Isim('Yusuf', 'Allah artırsın; Hz. Yûsuf.'),
  Isim('Yekta', 'Eşsiz, tek, benzersiz.'),
  Isim('Ahsen', 'En güzel, en iyi.'),
  Isim('Akif', 'İbadete yönelen, azimli; M. Âkif Ersoy.'),
  Isim('Bedirhan', 'Dolunay han; parlak lider.'),
  Isim('Bilal', 'Su, ıslaklık; ilk müezzin.'),
  Isim('Cengizhan', 'Güçlü hükümdar.'),
  Isim('Ediz', 'Yüce, değerli, ulu.'),
  Isim('Efe', 'Yiğit, zeybek, ağabey.'),
  Isim('Ekrem', 'En cömert, en şerefli.'),
  Isim('Enes', 'Cana yakın dost; sahâbe Enes bin Mâlik.'),
  Isim('Ferhan', 'Sevinçli, mutlu, neşeli.'),
  Isim('Gökhan', 'Gök hükümdarı.'),
  Isim('Halil', 'Samimi dost; Hz. İbrahim\'in lakabı.'),
  Isim('İzzet', 'Değer, şeref, yücelik.'),
  Isim('Kadir', 'Güçlü, değerli; Kadir gecesine izafeten.'),
  Isim('Levent', 'Boylu poslu, yakışıklı, denizci er.'),
  Isim('Mahir', 'Usta, becerikli, hünerli.'),
  Isim('Nedim', 'Sohbet arkadaşı, sırdaş.'),
  Isim('Onur', 'Şeref, haysiyet, izzetinefis.'),
  Isim('Rıza', 'Hoşnutluk, memnuniyet; Allah\'ın rızası.'),
  Isim('Samet', 'Hiçbir şeye muhtaç olmayan; Allah\'ın ismi.'),
  Isim('Sencer', 'Delen, nüfuz eden; Selçuklu sultanı.'),
  Isim('Serhat', 'Sınır boyu, hudut.'),
  Isim('Talha', 'Bir tür ağaç; cennetle müjdelenen sahâbe.'),
  Isim('Turhan', 'Soylu hükümdar.'),
  Isim('Ufuk', 'Göz alabildiğine uzanan sınır, çizgi.'),
  Isim('Volkan', 'Yanardağ; ateşli, coşkulu.'),
  Isim('Yusufcan', 'Yûsuf ile can birleşimi.'),
  Isim('Zafer', 'Galibiyet, üstün gelme.'),
];
