// Bilgi Yarışması soru bankası. Zorluk: 0=kolay, 1=orta, 2=çok zor.
// Her tur: 3 kolay + 3 orta + 4 çok zor = 10 soru rastgele seçilir.

class QuizQ {
  final String soru;
  final List<String> secenekler; // 4 şık
  final int dogru; // doğru şıkkın indexi (0-3)
  final int zorluk; // 0 kolay, 1 orta, 2 çok zor
  const QuizQ(this.soru, this.secenekler, this.dogru, this.zorluk);
}

const List<QuizQ> kQuizBank = [
  // ── KOLAY (zorluk 0) ──
  QuizQ('İslam\'ın ilk şartı nedir?',
      ['Namaz', 'Kelime-i şehadet', 'Oruç', 'Hac'], 1, 0),
  QuizQ('Günde kaç vakit namaz kılınır?', ['3', '5', '7', '4'], 1, 0),
  QuizQ('Kur\'an-ı Kerim kaç sûreden oluşur?', ['100', '114', '99', '120'], 1, 0),
  QuizQ('Ramazan ayında tutulan ibadet hangisidir?',
      ['Hac', 'Zekât', 'Oruç', 'Kurban'], 2, 0),
  QuizQ('Müslümanların kıblesi neresidir?',
      ['Mescid-i Aksa', 'Kâbe', 'Mescid-i Nebevî', 'Kudüs'], 1, 0),
  QuizQ('Peygamberimizin adı nedir?',
      ['İbrahim', 'Musa', 'Muhammed', 'İsa'], 2, 0),
  QuizQ('Kâbe hangi şehirdedir?',
      ['Medine', 'Mekke', 'Kudüs', 'İstanbul'], 1, 0),
  QuizQ('Kur\'an\'ın ilk sûresi hangisidir?',
      ['Bakara', 'İhlâs', 'Fâtiha', 'Nâs'], 2, 0),
  QuizQ('Zekât ne demektir?',
      ['Oruç tutmak', 'Malın belli bir kısmını vermek', 'Namaz kılmak', 'Hacca gitmek'],
      1, 0),
  QuizQ('Peygamberimiz hangi ayda doğmuştur?',
      ['Ramazan', 'Rebiülevvel', 'Şevval', 'Muharrem'], 1, 0),
  QuizQ('Bir Müslümanın günde okuması tavsiye edilen sûrelerden değildir?',
      ['İhlâs', 'Felak', 'Nâs', 'Tevrat'], 3, 0),
  QuizQ('Namaza başlarken alınan ilk tekbir nedir?',
      ['İftitah tekbiri', 'Teşrik tekbiri', 'Bayram tekbiri', 'Kunut'], 0, 0),
  QuizQ('İslam\'da haftalık toplu ibadet günü hangisidir?',
      ['Pazar', 'Cumartesi', 'Cuma', 'Pazartesi'], 2, 0),
  QuizQ('Hangisi meleklerdendir?',
      ['Cebrail', 'Ebu Cehil', 'Bilal', 'Ömer'], 0, 0),
  QuizQ('Oruç hangi vakitler arası tutulur?',
      ['Akşamdan sabaha', 'İmsaktan iftara', 'Öğleden akşama', 'Sabahtan öğlene'], 1, 0),
  QuizQ('Kurban Bayramı kaç gündür?',
      ['1', '2', '3', '4'], 2, 0),
  QuizQ('Peygamberimizin annesi kimdir?',
      ['Âmine', 'Hatice', 'Âişe', 'Fâtıma'], 0, 0),
  QuizQ('Hangisi abdest alırken yıkanan uzuvlardandır?',
      ['Diz', 'Yüz', 'Karın', 'Sırt'], 1, 0),
  QuizQ('İhlâs sûresinde neyden bahsedilir?',
      ['Cennet', 'Allah\'ın birliği (tevhid)', 'Kıyamet', 'Melekler'], 1, 0),
  QuizQ('Müslümanların kutsal kitabı nedir?',
      ['İncil', 'Tevrat', 'Kur\'an', 'Zebur'], 2, 0),
  QuizQ('Hangisi İslam\'ın şartlarından biri değildir?',
      ['Namaz', 'Oruç', 'Spor yapmak', 'Hac'], 2, 0),
  QuizQ('Fıtır sadakası (fitre) ne zaman verilir?',
      ['Kurban Bayramı', 'Ramazan Bayramı öncesi', 'Regaip', 'Aşure'], 1, 0),
  QuizQ('Peygamberimizin doğduğu yıla ne ad verilir?',
      ['Hicret yılı', 'Fil yılı', 'Veda yılı', 'Bedir yılı'], 1, 0),
  QuizQ('Namazda yönümüzü döndüğümüz yöne ne denir?',
      ['Kıble', 'Mihrap', 'Minber', 'Safa'], 0, 0),
  QuizQ('Hangisi büyük meleklerden biri değildir?',
      ['Cebrail', 'Mikail', 'İsrafil', 'Karun'], 3, 0),

  // ── ORTA (zorluk 1) ──
  QuizQ('Peygamberimize ilk vahiy nerede geldi?',
      ['Sevr Mağarası', 'Hira Mağarası', 'Uhud Dağı', 'Arafat'], 1, 1),
  QuizQ('Hicret hangi iki şehir arasında gerçekleşti?',
      ['Mekke-Taif', 'Mekke-Medine', 'Medine-Şam', 'Mekke-Kudüs'], 1, 1),
  QuizQ('Kur\'an\'daki en uzun sûre hangisidir?',
      ['Fâtiha', 'Bakara', 'Yâsîn', 'Kehf'], 1, 1),
  QuizQ('İlk müezzin kimdir?',
      ['Bilal-i Habeşî', 'Ebu Bekir', 'Selman-ı Farisî', 'Zeyd'], 0, 1),
  QuizQ('Bedir Savaşı hangi yıl gerçekleşti?',
      ['Hicretin 1. yılı', 'Hicretin 2. yılı', 'Hicretin 5. yılı', 'Hicretin 8. yılı'], 1, 1),
  QuizQ('Kur\'an kaç yılda tamamlanmıştır (yaklaşık)?',
      ['10 yıl', '23 yıl', '40 yıl', '5 yıl'], 1, 1),
  QuizQ('Hangi sahâbe "Faruk" lakabıyla bilinir?',
      ['Ebu Bekir', 'Ömer', 'Osman', 'Ali'], 1, 1),
  QuizQ('Mescid-i Nebevî hangi şehirdedir?',
      ['Mekke', 'Medine', 'Kudüs', 'Kûfe'], 1, 1),
  QuizQ('"Seyyidü\'l-İstiğfar" ne anlama gelir?',
      ['Duaların efendisi', 'İstiğfarların efendisi', 'Namazların efendisi', 'Sûrelerin efendisi'],
      1, 1),
  QuizQ('Kur\'an\'da ismi geçen tek kadın kimdir?',
      ['Hz. Hatice', 'Hz. Meryem', 'Hz. Âişe', 'Hz. Fâtıma'], 1, 1),
  QuizQ('Kâbe\'yi ilk inşa eden peygamber kimdir (rivayete göre)?',
      ['Hz. İbrahim', 'Hz. Âdem', 'Hz. Nuh', 'Hz. İsmail'], 1, 1),
  QuizQ('Hangi gece "bin aydan hayırlı" olarak nitelenir?',
      ['Berat', 'Mirac', 'Kadir', 'Regaip'], 2, 1),
  QuizQ('Peygamberimizin süt annesi kimdir?',
      ['Halime', 'Âmine', 'Şifa', 'Süveybe'], 0, 1),
  QuizQ('İfk hadisesi hangi hanımla ilgilidir?',
      ['Hz. Hatice', 'Hz. Âişe', 'Hz. Zeynep', 'Hz. Hafsa'], 1, 1),
  QuizQ('Kur\'an\'ı çoğaltıp beldelere gönderen halife kimdir?',
      ['Ebu Bekir', 'Ömer', 'Osman', 'Ali'], 2, 1),
  QuizQ('"Zülkarneyn" kıssası hangi sûrede geçer?',
      ['Yâsîn', 'Kehf', 'Meryem', 'Tâhâ'], 1, 1),
  QuizQ('Hangi savaşta Müslümanlar hendek kazdı?',
      ['Bedir', 'Uhud', 'Hendek (Ahzab)', 'Huneyn'], 2, 1),
  QuizQ('Namazda "kade" ne demektir?',
      ['Ayakta durmak', 'Oturmak', 'Rükûa gitmek', 'Secde etmek'], 1, 1),
  QuizQ('Peygamberimizin en küçük kızı kimdir?',
      ['Zeynep', 'Rukiye', 'Ümmü Gülsüm', 'Fâtıma'], 3, 1),
  QuizQ('Hz. Yusuf hangi ülkede vezir oldu?',
      ['Şam', 'Mısır', 'Yemen', 'Irak'], 1, 1),
  QuizQ('İslam\'da ilk yapılan mescit hangisidir?',
      ['Mescid-i Haram', 'Mescid-i Nebevî', 'Kuba Mescidi', 'Mescid-i Aksa'], 2, 1),
  QuizQ('Kur\'an\'ın kalbi sayılan sûre hangisidir?',
      ['Fâtiha', 'Yâsîn', 'İhlâs', 'Rahmân'], 1, 1),
  QuizQ('Veda Haccı hangi yıl yapıldı?',
      ['Hicretin 6. yılı', 'Hicretin 8. yılı', 'Hicretin 10. yılı', 'Hicretin 2. yılı'], 2, 1),
  QuizQ('Hangi sahâbe "İslam\'ın kılıcı" lakabıyla anılır?',
      ['Halid bin Velid', 'Sa\'d bin Ebî Vakkas', 'Talha', 'Zübeyr'], 0, 1),
  QuizQ('Cebrail\'in Kur\'an\'daki bir diğer adı nedir?',
      ['Rûhu\'l-Kudüs', 'Melekü\'l-Mevt', 'Rıdvan', 'Malik'], 0, 1),

  // ── ÇOK ZOR (zorluk 2) ──
  QuizQ('Kur\'an\'da kaç âyet vardır (en yaygın sayıma göre)?',
      ['6236', '6666', '6000', '5500'], 0, 2),
  QuizQ('"Ashâb-ı Kehf" kaç kişiydi (yaygın rivayete göre köpekleriyle)?',
      ['5', '7 (+köpek)', '9', '12'], 1, 2),
  QuizQ('Secde âyeti Kur\'an\'da kaç yerde geçer?',
      ['10', '14', '20', '7'], 1, 2),
  QuizQ('Peygamberimizin künyesi (Ebu ...) nedir?',
      ['Ebu Kasım', 'Ebu Talib', 'Ebu Bekir', 'Ebu Hureyre'], 0, 2),
  QuizQ('Hicri takvim hangi halife döneminde başlatıldı?',
      ['Ebu Bekir', 'Ömer', 'Osman', 'Ali'], 1, 2),
  QuizQ('Kur\'an\'da "besmele" kaç kez geçer (Neml dâhil)?',
      ['114', '113', '115', '112'], 0, 2),
  QuizQ('Hangi sûre "besmele" ile başlamaz?',
      ['Fâtiha', 'Tevbe (Berâe)', 'Bakara', 'Nâs'], 1, 2),
  QuizQ('İlk Cuma namazı nerede kılındı?',
      ['Mekke', 'Kuba yakınında Ranuna vadisi', 'Medine merkez', 'Taif'], 1, 2),
  QuizQ('Kur\'an\'da adı en çok geçen peygamber kimdir?',
      ['Hz. İbrahim', 'Hz. Musa', 'Hz. İsa', 'Hz. Nuh'], 1, 2),
  QuizQ('"Mekke\'nin Fethi" hangi yıl gerçekleşti?',
      ['Hicretin 6. yılı', 'Hicretin 8. yılı', 'Hicretin 9. yılı', 'Hicretin 10. yılı'], 1, 2),
  QuizQ('Kur\'an\'daki en kısa sûre kaç âyettir?',
      ['3 (Kevser)', '4', '5', '2'], 0, 2),
  QuizQ('Hangi sahâbe "Kur\'an\'ı en iyi okuyan" olarak anılır?',
      ['Übey bin Kâ\'b', 'Ebu Zer', 'Muâz bin Cebel', 'Enes'], 0, 2),
  QuizQ('Uhud Savaşı\'nda şehit edilen Peygamber\'in amcası kimdir?',
      ['Ebu Talib', 'Hamza', 'Abbas', 'Ebu Leheb'], 1, 2),
  QuizQ('Kur\'an\'da "Ümmü\'l-Kitâb" (Kitabın anası) denilen sûre hangisidir?',
      ['Yâsîn', 'Fâtiha', 'Bakara', 'İhlâs'], 1, 2),
  QuizQ('Miladi hangi yıl "Fil Vakası" yaşandı (Peygamberimizin doğumu)?',
      ['571', '610', '622', '632'], 0, 2),
  QuizQ('Hangi peygamber "Kelîmullah" (Allah ile konuşan) lakabıyla anılır?',
      ['Hz. İbrahim', 'Hz. Musa', 'Hz. İsa', 'Hz. Âdem'], 1, 2),
  QuizQ('Kur\'an\'da hakkında müstakil sûre bulunan hayvan hangisidir?',
      ['Deve', 'Karınca ve arı (Neml/Nahl)', 'At', 'Koyun'], 1, 2),
  QuizQ('İlk vahiy hangi sûrenin ilk âyetleridir?',
      ['Fâtiha', 'Müddessir', 'Alak', 'Kalem'], 2, 2),
  QuizQ('Peygamberimiz kaç yaşında peygamber oldu?',
      ['25', '40', '53', '63'], 1, 2),
  QuizQ('Hangi savaş "Furkan günü" olarak da anılır?',
      ['Uhud', 'Bedir', 'Hendek', 'Mûte'], 1, 2),
  QuizQ('Kur\'an\'da ismi geçen tek sahâbî kimdir?',
      ['Ebu Bekir', 'Ömer', 'Zeyd bin Hârise', 'Ali'], 2, 2),
  QuizQ('Cennetle müjdelenen on sahâbeye ne denir?',
      ['Ehl-i Bedir', 'Aşere-i Mübeşşere', 'Ehl-i Suffe', 'Muhâcirûn'], 1, 2),
  QuizQ('Kur\'an\'da "tebbet" ile başlayan sûre kime hitap eder?',
      ['Ebu Cehil', 'Ebu Leheb', 'Ümeyye', 'Velid'], 1, 2),
  QuizQ('Namaz kaç yılında (hicretten önce) farz kılındı?',
      ['Mirac gecesi, hicretten ~1.5 yıl önce', 'Bedir sonrası', 'Hicretin 2. yılı', 'İlk vahiyde'],
      0, 2),
  QuizQ('Hz. Ömer\'in İslam\'a girmesine vesile olan sûre hangisidir?',
      ['Yâsîn', 'Tâhâ', 'Rahmân', 'Vâkıa'], 1, 2),
];
