// Arapça Sözlük — Türkçe ↔ Arapça. Her giriş: Arapça yazım + okunuş + Türkçe.
// Arama hem Türkçeden hem okunuştan/Arapçadan yapılabilir.

class SozlukKelime {
  final String arabic; // Arapça yazım (harekeli)
  final String okunus; // Latin okunuş
  final String turkce; // Türkçe karşılık
  const SozlukKelime(this.arabic, this.okunus, this.turkce);
}

const List<SozlukKelime> kSozluk = [
  // Din / iman
  SozlukKelime('اللّٰه', 'Allâh', 'Allah'),
  SozlukKelime('دِين', 'dîn', 'din'),
  SozlukKelime('إِيمَان', 'îmân', 'iman, inanç'),
  SozlukKelime('إِسْلَام', 'islâm', 'İslam, teslimiyet'),
  SozlukKelime('صَلَاة', 'salât', 'namaz'),
  SozlukKelime('صَوْم', 'savm', 'oruç'),
  SozlukKelime('زَكَاة', 'zekât', 'zekât'),
  SozlukKelime('حَجّ', 'hacc', 'hac'),
  SozlukKelime('دُعَاء', 'duâ', 'dua'),
  SozlukKelime('ذِكْر', 'zikr', 'zikir, anma'),
  SozlukKelime('قُرْآن', 'kur\'ân', 'Kur\'an'),
  SozlukKelime('آيَة', 'âyet', 'ayet, işaret'),
  SozlukKelime('سُورَة', 'sûre', 'sure'),
  SozlukKelime('مَسْجِد', 'mescid', 'mescit, cami'),
  SozlukKelime('قِبْلَة', 'kıble', 'kıble'),
  SozlukKelime('جَنَّة', 'cennet', 'cennet, bahçe'),
  SozlukKelime('نَار', 'nâr', 'ateş, cehennem'),
  SozlukKelime('مَلَك', 'melek', 'melek'),
  SozlukKelime('نَبِيّ', 'nebî', 'peygamber'),
  SozlukKelime('رَسُول', 'resûl', 'elçi, resul'),
  SozlukKelime('عَبْد', 'abd', 'kul'),
  SozlukKelime('رَبّ', 'rabb', 'Rab, terbiye eden'),
  SozlukKelime('تَوْبَة', 'tevbe', 'tövbe'),
  SozlukKelime('شُكْر', 'şükr', 'şükür'),
  SozlukKelime('صَبْر', 'sabr', 'sabır'),
  SozlukKelime('رَحْمَة', 'rahmet', 'merhamet, rahmet'),
  SozlukKelime('مَغْفِرَة', 'mağfiret', 'bağışlanma'),
  SozlukKelime('بَرَكَة', 'bereket', 'bereket'),
  SozlukKelime('حَلَال', 'helâl', 'helal'),
  SozlukKelime('حَرَام', 'harâm', 'haram'),

  // Zaman
  SozlukKelime('يَوْم', 'yevm', 'gün'),
  SozlukKelime('لَيْل', 'leyl', 'gece'),
  SozlukKelime('نَهَار', 'nehâr', 'gündüz'),
  SozlukKelime('صَبَاح', 'sabâh', 'sabah'),
  SozlukKelime('مَسَاء', 'mesâ', 'akşam'),
  SozlukKelime('أُسْبُوع', 'usbû', 'hafta'),
  SozlukKelime('شَهْر', 'şehr', 'ay (takvim)'),
  SozlukKelime('سَنَة', 'sene', 'yıl'),
  SozlukKelime('سَاعَة', 'sâat', 'saat'),
  SozlukKelime('وَقْت', 'vakt', 'vakit, zaman'),
  SozlukKelime('الْيَوْمَ', 'el-yevme', 'bugün'),
  SozlukKelime('غَدًا', 'ğaden', 'yarın'),
  SozlukKelime('أَمْس', 'ems', 'dün'),

  // Doğa
  SozlukKelime('سَمَاء', 'semâ', 'gökyüzü'),
  SozlukKelime('أَرْض', 'ard', 'yer, toprak'),
  SozlukKelime('شَمْس', 'şems', 'güneş'),
  SozlukKelime('قَمَر', 'kamer', 'ay (gökyüzü)'),
  SozlukKelime('نَجْم', 'necm', 'yıldız'),
  SozlukKelime('بَحْر', 'bahr', 'deniz'),
  SozlukKelime('نَهْر', 'nehr', 'nehir'),
  SozlukKelime('جَبَل', 'cebel', 'dağ'),
  SozlukKelime('مَاء', 'mâ', 'su'),
  SozlukKelime('نَار', 'nâr', 'ateş'),
  SozlukKelime('رِيح', 'rîh', 'rüzgâr'),
  SozlukKelime('مَطَر', 'matar', 'yağmur'),
  SozlukKelime('شَجَر', 'şecer', 'ağaç'),
  SozlukKelime('وَرْد', 'verd', 'gül'),
  SozlukKelime('زَهْرَة', 'zehre', 'çiçek'),
  SozlukKelime('حَجَر', 'hacer', 'taş'),
  SozlukKelime('تُرَاب', 'türâb', 'toprak'),
  SozlukKelime('ذَهَب', 'zeheb', 'altın'),

  // Aile / insan
  SozlukKelime('إِنْسَان', 'insân', 'insan'),
  SozlukKelime('رَجُل', 'racül', 'adam, erkek'),
  SozlukKelime('اِمْرَأَة', 'imrae', 'kadın'),
  SozlukKelime('أَب', 'eb', 'baba'),
  SozlukKelime('أُمّ', 'ümm', 'anne'),
  SozlukKelime('اِبْن', 'ibn', 'oğul'),
  SozlukKelime('بِنْت', 'bint', 'kız'),
  SozlukKelime('أَخ', 'ah', 'erkek kardeş'),
  SozlukKelime('أُخْت', 'uht', 'kız kardeş'),
  SozlukKelime('زَوْج', 'zevc', 'eş (koca)'),
  SozlukKelime('زَوْجَة', 'zevce', 'eş (hanım)'),
  SozlukKelime('وَلَد', 'veled', 'çocuk'),
  SozlukKelime('صَدِيق', 'sadîk', 'arkadaş'),
  SozlukKelime('جَار', 'câr', 'komşu'),
  SozlukKelime('مَلِك', 'melik', 'hükümdar'),
  SozlukKelime('ضَيْف', 'dayf', 'misafir'),

  // Beden
  SozlukKelime('قَلْب', 'kalb', 'kalp'),
  SozlukKelime('رُوح', 'rûh', 'ruh'),
  SozlukKelime('رَأْس', 're\'s', 'baş'),
  SozlukKelime('عَيْن', 'ayn', 'göz'),
  SozlukKelime('أُذُن', 'üzün', 'kulak'),
  SozlukKelime('أَنْف', 'enf', 'burun'),
  SozlukKelime('فَم', 'fem', 'ağız'),
  SozlukKelime('لِسَان', 'lisân', 'dil'),
  SozlukKelime('يَد', 'yed', 'el'),
  SozlukKelime('رِجْل', 'ricl', 'ayak'),
  SozlukKelime('قَدَم', 'kadem', 'ayak (taban)'),
  SozlukKelime('دَم', 'dem', 'kan'),
  SozlukKelime('وَجْه', 'vech', 'yüz'),

  // Kavramlar / duygular
  SozlukKelime('عِلْم', 'ilm', 'ilim, bilgi'),
  SozlukKelime('حِكْمَة', 'hikmet', 'hikmet'),
  SozlukKelime('حَقّ', 'hakk', 'hak, gerçek'),
  SozlukKelime('عَدْل', 'adl', 'adalet'),
  SozlukKelime('خَيْر', 'hayr', 'iyilik, hayır'),
  SozlukKelime('شَرّ', 'şerr', 'kötülük'),
  SozlukKelime('حُبّ', 'hubb', 'sevgi'),
  SozlukKelime('مَحَبَّة', 'mahabbe', 'muhabbet, sevgi'),
  SozlukKelime('سَلَام', 'selâm', 'barış, esenlik'),
  SozlukKelime('حَرْب', 'harb', 'savaş'),
  SozlukKelime('قُوَّة', 'kuvvet', 'güç'),
  SozlukKelime('صِدْق', 'sıdk', 'doğruluk'),
  SozlukKelime('كَذِب', 'kizb', 'yalan'),
  SozlukKelime('أَمَل', 'emel', 'umut'),
  SozlukKelime('خَوْف', 'havf', 'korku'),
  SozlukKelime('فَرَح', 'ferah', 'sevinç'),
  SozlukKelime('حُزْن', 'hüzn', 'hüzün'),
  SozlukKelime('نُور', 'nûr', 'ışık, nur'),
  SozlukKelime('ظُلْمَة', 'zulmet', 'karanlık'),
  SozlukKelime('صِحَّة', 'sıhha', 'sağlık'),

  // Günlük eşya / yer
  SozlukKelime('بَيْت', 'beyt', 'ev'),
  SozlukKelime('بَاب', 'bâb', 'kapı'),
  SozlukKelime('طَرِيق', 'tarîk', 'yol'),
  SozlukKelime('مَدِينَة', 'medîne', 'şehir'),
  SozlukKelime('سُوق', 'sûk', 'çarşı, pazar'),
  SozlukKelime('كِتَاب', 'kitâb', 'kitap'),
  SozlukKelime('قَلَم', 'kalem', 'kalem'),
  SozlukKelime('مَال', 'mâl', 'mal, para'),
  SozlukKelime('طَعَام', 'taâm', 'yemek'),
  SozlukKelime('خُبْز', 'hubz', 'ekmek'),
  SozlukKelime('لَبَن', 'leben', 'süt'),
  SozlukKelime('عَسَل', 'asel', 'bal'),
  SozlukKelime('لَحْم', 'lahm', 'et'),
  SozlukKelime('بَاب', 'bâb', 'kapı'),
  SozlukKelime('ثَوْب', 'sevb', 'elbise'),
  SozlukKelime('لِبَاس', 'libâs', 'giysi'),

  // Fiiller (mastar)
  SozlukKelime('قِرَاءَة', 'kırâe', 'okuma'),
  SozlukKelime('كِتَابَة', 'kitâbe', 'yazma'),
  SozlukKelime('عَمَل', 'amel', 'iş, amel'),
  SozlukKelime('سَفَر', 'sefer', 'yolculuk'),
  SozlukKelime('نَوْم', 'nevm', 'uyku'),
  SozlukKelime('أَكْل', 'ekl', 'yeme'),
  SozlukKelime('شُرْب', 'şürb', 'içme'),
  SozlukKelime('كَلَام', 'kelâm', 'söz, konuşma'),
  SozlukKelime('سُؤَال', 'suâl', 'soru'),
  SozlukKelime('جَوَاب', 'cevâb', 'cevap'),

  // Sayılar
  SozlukKelime('وَاحِد', 'vâhid', 'bir (1)'),
  SozlukKelime('اِثْنَان', 'isnân', 'iki (2)'),
  SozlukKelime('ثَلَاثَة', 'selâse', 'üç (3)'),
  SozlukKelime('أَرْبَعَة', 'erbaa', 'dört (4)'),
  SozlukKelime('خَمْسَة', 'hamse', 'beş (5)'),
  SozlukKelime('سِتَّة', 'sitte', 'altı (6)'),
  SozlukKelime('سَبْعَة', 'seb\'a', 'yedi (7)'),
  SozlukKelime('ثَمَانِيَة', 'semâniye', 'sekiz (8)'),
  SozlukKelime('تِسْعَة', 'tis\'a', 'dokuz (9)'),
  SozlukKelime('عَشَرَة', 'aşera', 'on (10)'),
  SozlukKelime('مِائَة', 'mie', 'yüz (100)'),
  SozlukKelime('أَلْف', 'elf', 'bin (1000)'),
];
