// Arapça Sözlük — Türkçe ↔ Arapça. Her giriş: Arapça yazım + okunuş + Türkçe.
// Arama hem Türkçeden hem okunuştan/Arapçadan yapılabilir.

class SozlukKelime {
  final String arabic; // Arapça yazım (harekeli)
  final String okunus; // Latin okunuş
  final String turkce; // Türkçe karşılık
  const SozlukKelime(this.arabic, this.okunus, this.turkce);
}

const List<SozlukKelime> kSozluk = [
  // Din / iman
  SozlukKelime('اللّٰه', 'Allâh', 'Allah'),
  SozlukKelime('دِين', 'dîn', 'din'),
  SozlukKelime('إِيمَان', 'îmân', 'iman, inanç'),
  SozlukKelime('إِسْلَام', 'islâm', 'İslam, teslimiyet'),
  SozlukKelime('صَلَاة', 'salât', 'namaz'),
  SozlukKelime('صَوْم', 'savm', 'oruç'),
  SozlukKelime('زَكَاة', 'zekât', 'zekât'),
  SozlukKelime('حَجّ', 'hacc', 'hac'),
  SozlukKelime('دُعَاء', 'duâ', 'dua'),
  SozlukKelime('ذِكْر', 'zikr', 'zikir, anma'),
  SozlukKelime('قُرْآن', 'kur\'ân', 'Kur\'an'),
  SozlukKelime('آيَة', 'âyet', 'ayet, işaret'),
  SozlukKelime('سُورَة', 'sûre', 'sure'),
  SozlukKelime('مَسْجِد', 'mescid', 'mescit, cami'),
  SozlukKelime('قِبْلَة', 'kıble', 'kıble'),
  SozlukKelime('جَنَّة', 'cennet', 'cennet, bahçe'),
  SozlukKelime('نَار', 'nâr', 'ateş, cehennem'),
  SozlukKelime('مَلَك', 'melek', 'melek'),
  SozlukKelime('نَبِيّ', 'nebî', 'peygamber'),
  SozlukKelime('رَسُول', 'resûl', 'elçi, resul'),
  SozlukKelime('عَبْد', 'abd', 'kul'),
  SozlukKelime('رَبّ', 'rabb', 'Rab, terbiye eden'),
  SozlukKelime('تَوْبَة', 'tevbe', 'tövbe'),
  SozlukKelime('شُكْر', 'şükr', 'şükür'),
  SozlukKelime('صَبْر', 'sabr', 'sabır'),
  SozlukKelime('رَحْمَة', 'rahmet', 'merhamet, rahmet'),
  SozlukKelime('مَغْفِرَة', 'mağfiret', 'bağışlanma'),
  SozlukKelime('بَرَكَة', 'bereket', 'bereket'),
  SozlukKelime('حَلَال', 'helâl', 'helal'),
  SozlukKelime('حَرَام', 'harâm', 'haram'),

  // Zaman
  SozlukKelime('يَوْم', 'yevm', 'gün'),
  SozlukKelime('لَيْل', 'leyl', 'gece'),
  SozlukKelime('نَهَار', 'nehâr', 'gündüz'),
  SozlukKelime('صَبَاح', 'sabâh', 'sabah'),
  SozlukKelime('مَسَاء', 'mesâ', 'akşam'),
  SozlukKelime('أُسْبُوع', 'usbû', 'hafta'),
  SozlukKelime('شَهْر', 'şehr', 'ay (takvim)'),
  SozlukKelime('سَنَة', 'sene', 'yıl'),
  SozlukKelime('سَاعَة', 'sâat', 'saat'),
  SozlukKelime('وَقْت', 'vakt', 'vakit, zaman'),
  SozlukKelime('الْيَوْمَ', 'el-yevme', 'bugün'),
  SozlukKelime('غَدًا', 'ğaden', 'yarın'),
  SozlukKelime('أَمْس', 'ems', 'dün'),

  // Doğa
  SozlukKelime('سَمَاء', 'semâ', 'gökyüzü'),
  SozlukKelime('أَرْض', 'ard', 'yer, toprak'),
  SozlukKelime('شَمْس', 'şems', 'güneş'),
  SozlukKelime('قَمَر', 'kamer', 'ay (gökyüzü)'),
  SozlukKelime('نَجْم', 'necm', 'yıldız'),
  SozlukKelime('بَحْر', 'bahr', 'deniz'),
  SozlukKelime('نَهْر', 'nehr', 'nehir'),
  SozlukKelime('جَبَل', 'cebel', 'dağ'),
  SozlukKelime('مَاء', 'mâ', 'su'),
  SozlukKelime('نَار', 'nâr', 'ateş'),
  SozlukKelime('رِيح', 'rîh', 'rüzgâr'),
  SozlukKelime('مَطَر', 'matar', 'yağmur'),
  SozlukKelime('شَجَر', 'şecer', 'ağaç'),
  SozlukKelime('وَرْد', 'verd', 'gül'),
  SozlukKelime('زَهْرَة', 'zehre', 'çiçek'),
  SozlukKelime('حَجَر', 'hacer', 'taş'),
  SozlukKelime('تُرَاب', 'türâb', 'toprak'),
  SozlukKelime('ذَهَب', 'zeheb', 'altın'),

  // Aile / insan
  SozlukKelime('إِنْسَان', 'insân', 'insan'),
  SozlukKelime('رَجُل', 'racül', 'adam, erkek'),
  SozlukKelime('اِمْرَأَة', 'imrae', 'kadın'),
  SozlukKelime('أَب', 'eb', 'baba'),
  SozlukKelime('أُمّ', 'ümm', 'anne'),
  SozlukKelime('اِبْن', 'ibn', 'oğul'),
  SozlukKelime('بِنْت', 'bint', 'kız'),
  SozlukKelime('أَخ', 'ah', 'erkek kardeş'),
  SozlukKelime('أُخْت', 'uht', 'kız kardeş'),
  SozlukKelime('زَوْج', 'zevc', 'eş (koca)'),
  SozlukKelime('زَوْجَة', 'zevce', 'eş (hanım)'),
  SozlukKelime('وَلَد', 'veled', 'çocuk'),
  SozlukKelime('صَدِيق', 'sadîk', 'arkadaş'),
  SozlukKelime('جَار', 'câr', 'komşu'),
  SozlukKelime('مَلِك', 'melik', 'hükümdar'),
  SozlukKelime('ضَيْف', 'dayf', 'misafir'),

  // Beden
  SozlukKelime('قَلْب', 'kalb', 'kalp'),
  SozlukKelime('رُوح', 'rûh', 'ruh'),
  SozlukKelime('رَأْس', 're\'s', 'baş'),
  SozlukKelime('عَيْن', 'ayn', 'göz'),
  SozlukKelime('أُذُن', 'üzün', 'kulak'),
  SozlukKelime('أَنْف', 'enf', 'burun'),
  SozlukKelime('فَم', 'fem', 'ağız'),
  SozlukKelime('لِسَان', 'lisân', 'dil'),
  SozlukKelime('يَد', 'yed', 'el'),
  SozlukKelime('رِجْل', 'ricl', 'ayak'),
  SozlukKelime('قَدَم', 'kadem', 'ayak (taban)'),
  SozlukKelime('دَم', 'dem', 'kan'),
  SozlukKelime('وَجْه', 'vech', 'yüz'),

  // Kavramlar / duygular
  SozlukKelime('عِلْم', 'ilm', 'ilim, bilgi'),
  SozlukKelime('حِكْمَة', 'hikmet', 'hikmet'),
  SozlukKelime('حَقّ', 'hakk', 'hak, gerçek'),
  SozlukKelime('عَدْل', 'adl', 'adalet'),
  SozlukKelime('خَيْر', 'hayr', 'iyilik, hayır'),
  SozlukKelime('شَرّ', 'şerr', 'kötülük'),
  SozlukKelime('حُبّ', 'hubb', 'sevgi'),
  SozlukKelime('مَحَبَّة', 'mahabbe', 'muhabbet, sevgi'),
  SozlukKelime('سَلَام', 'selâm', 'barış, esenlik'),
  SozlukKelime('حَرْب', 'harb', 'savaş'),
  SozlukKelime('قُوَّة', 'kuvvet', 'güç'),
  SozlukKelime('صِدْق', 'sıdk', 'doğruluk'),
  SozlukKelime('كَذِب', 'kizb', 'yalan'),
  SozlukKelime('أَمَل', 'emel', 'umut'),
  SozlukKelime('خَوْف', 'havf', 'korku'),
  SozlukKelime('فَرَح', 'ferah', 'sevinç'),
  SozlukKelime('حُزْن', 'hüzn', 'hüzün'),
  SozlukKelime('نُور', 'nûr', 'ışık, nur'),
  SozlukKelime('ظُلْمَة', 'zulmet', 'karanlık'),
  SozlukKelime('صِحَّة', 'sıhha', 'sağlık'),

  // Günlük eşya / yer
  SozlukKelime('بَيْت', 'beyt', 'ev'),
  SozlukKelime('بَاب', 'bâb', 'kapı'),
  SozlukKelime('طَرِيق', 'tarîk', 'yol'),
  SozlukKelime('مَدِينَة', 'medîne', 'şehir'),
  SozlukKelime('سُوق', 'sûk', 'çarşı, pazar'),
  SozlukKelime('كِتَاب', 'kitâb', 'kitap'),
  SozlukKelime('قَلَم', 'kalem', 'kalem'),
  SozlukKelime('مَال', 'mâl', 'mal, para'),
  SozlukKelime('طَعَام', 'taâm', 'yemek'),
  SozlukKelime('خُبْز', 'hubz', 'ekmek'),
  SozlukKelime('لَبَن', 'leben', 'süt'),
  SozlukKelime('عَسَل', 'asel', 'bal'),
  SozlukKelime('لَحْم', 'lahm', 'et'),
  SozlukKelime('بَاب', 'bâb', 'kapı'),
  SozlukKelime('ثَوْب', 'sevb', 'elbise'),
  SozlukKelime('لِبَاس', 'libâs', 'giysi'),

  // Fiiller (mastar)
  SozlukKelime('قِرَاءَة', 'kırâe', 'okuma'),
  SozlukKelime('كِتَابَة', 'kitâbe', 'yazma'),
  SozlukKelime('عَمَل', 'amel', 'iş, amel'),
  SozlukKelime('سَفَر', 'sefer', 'yolculuk'),
  SozlukKelime('نَوْم', 'nevm', 'uyku'),
  SozlukKelime('أَكْل', 'ekl', 'yeme'),
  SozlukKelime('شُرْب', 'şürb', 'içme'),
  SozlukKelime('كَلَام', 'kelâm', 'söz, konuşma'),
  SozlukKelime('سُؤَال', 'suâl', 'soru'),
  SozlukKelime('جَوَاب', 'cevâb', 'cevap'),

  // Sayılar
  SozlukKelime('وَاحِد', 'vâhid', 'bir (1)'),
  SozlukKelime('اِثْنَان', 'isnân', 'iki (2)'),
  SozlukKelime('ثَلَاثَة', 'selâse', 'üç (3)'),
  SozlukKelime('أَرْبَعَة', 'erbaa', 'dört (4)'),
  SozlukKelime('خَمْسَة', 'hamse', 'beş (5)'),
  SozlukKelime('سِتَّة', 'sitte', 'altı (6)'),
  SozlukKelime('سَبْعَة', 'seb\'a', 'yedi (7)'),
  SozlukKelime('ثَمَانِيَة', 'semâniye', 'sekiz (8)'),
  SozlukKelime('تِسْعَة', 'tis\'a', 'dokuz (9)'),
  SozlukKelime('عَشَرَة', 'aşera', 'on (10)'),
  SozlukKelime('مِائَة', 'mie', 'yüz (100)'),
  SozlukKelime('أَلْف', 'elf', 'bin (1000)'),

  // ── Renkler ──
  SozlukKelime('لَوْن', 'levn', 'renk'),
  SozlukKelime('أَبْيَض', 'ebyad', 'beyaz'),
  SozlukKelime('أَسْوَد', 'esved', 'siyah'),
  SozlukKelime('أَحْمَر', 'ahmer', 'kırmızı'),
  SozlukKelime('أَخْضَر', 'ahdar', 'yeşil'),
  SozlukKelime('أَزْرَق', 'ezrak', 'mavi'),
  SozlukKelime('أَصْفَر', 'asfar', 'sarı'),
  SozlukKelime('بُنِّيّ', 'bünnî', 'kahverengi'),
  SozlukKelime('رَمَادِيّ', 'ramâdî', 'gri'),
  SozlukKelime('وَرْدِيّ', 'verdî', 'pembe'),
  SozlukKelime('ذَهَبِيّ', 'zehebî', 'altın rengi'),
  SozlukKelime('فِضِّيّ', 'fıddî', 'gümüş rengi'),

  // ── Fiiller (yaygın) ──
  SozlukKelime('قَرَأَ', 'karae', 'okudu'),
  SozlukKelime('كَتَبَ', 'ketebe', 'yazdı'),
  SozlukKelime('سَمِعَ', 'semia', 'işitti'),
  SozlukKelime('رَأَى', 'raâ', 'gördü'),
  SozlukKelime('قَالَ', 'kâle', 'dedi'),
  SozlukKelime('فَعَلَ', 'feale', 'yaptı'),
  SozlukKelime('عَمِلَ', 'amile', 'çalıştı, yaptı'),
  SozlukKelime('ذَهَبَ', 'zehebe', 'gitti'),
  SozlukKelime('جَاءَ', 'câe', 'geldi'),
  SozlukKelime('أَكَلَ', 'ekele', 'yedi'),
  SozlukKelime('شَرِبَ', 'şeribe', 'içti'),
  SozlukKelime('نَامَ', 'nâme', 'uyudu'),
  SozlukKelime('جَلَسَ', 'celese', 'oturdu'),
  SozlukKelime('وَقَفَ', 'vakafe', 'ayakta durdu'),
  SozlukKelime('مَشَى', 'meşâ', 'yürüdü'),
  SozlukKelime('رَكِبَ', 'rakibe', 'bindi'),
  SozlukKelime('خَرَجَ', 'harace', 'çıktı'),
  SozlukKelime('دَخَلَ', 'dehale', 'girdi'),
  SozlukKelime('فَتَحَ', 'fetaha', 'açtı'),
  SozlukKelime('أَغْلَقَ', 'ağleka', 'kapattı'),
  SozlukKelime('عَرَفَ', 'arafe', 'bildi, tanıdı'),
  SozlukKelime('عَلِمَ', 'alime', 'bildi'),
  SozlukKelime('فَهِمَ', 'fehime', 'anladı'),
  SozlukKelime('سَأَلَ', 'seele', 'sordu'),
  SozlukKelime('أَجَابَ', 'ecâbe', 'cevap verdi'),
  SozlukKelime('طَلَبَ', 'talebe', 'istedi'),
  SozlukKelime('وَجَدَ', 'vecede', 'buldu'),
  SozlukKelime('أَخَذَ', 'ehaze', 'aldı'),
  SozlukKelime('أَعْطَى', 'a\'tâ', 'verdi'),
  SozlukKelime('حَمَلَ', 'hamele', 'taşıdı'),
  SozlukKelime('وَضَعَ', 'vadaa', 'koydu'),
  SozlukKelime('بَدَأَ', 'bedee', 'başladı'),
  SozlukKelime('اِنْتَهَى', 'intehâ', 'bitti'),
  SozlukKelime('عَادَ', 'âde', 'döndü'),
  SozlukKelime('بَقِيَ', 'bakiye', 'kaldı'),
  SozlukKelime('صَنَعَ', 'sanaa', 'yaptı, üretti'),
  SozlukKelime('بَنَى', 'benâ', 'inşa etti'),
  SozlukKelime('حَفِظَ', 'hafiza', 'korudu, ezberledi'),
  SozlukKelime('نَسِيَ', 'nesiye', 'unuttu'),
  SozlukKelime('ذَكَرَ', 'zekere', 'andı, hatırladı'),
  SozlukKelime('أَحَبَّ', 'ehabbe', 'sevdi'),
  SozlukKelime('كَرِهَ', 'kerihe', 'hoşlanmadı'),
  SozlukKelime('ضَحِكَ', 'dahike', 'güldü'),
  SozlukKelime('بَكَى', 'bekâ', 'ağladı'),
  SozlukKelime('خَافَ', 'hâfe', 'korktu'),
  SozlukKelime('فَرِحَ', 'fariha', 'sevindi'),
  SozlukKelime('غَضِبَ', 'gadibe', 'öfkelendi'),
  SozlukKelime('صَبَرَ', 'sabere', 'sabretti'),
  SozlukKelime('شَكَرَ', 'şekere', 'şükretti'),
  SozlukKelime('دَعَا', 'deâ', 'dua etti, çağırdı'),
  SozlukKelime('صَلَّى', 'sallâ', 'namaz kıldı'),
  SozlukKelime('صَامَ', 'sâme', 'oruç tuttu'),
  SozlukKelime('سَجَدَ', 'secede', 'secde etti'),
  SozlukKelime('غَفَرَ', 'gafere', 'bağışladı'),
  SozlukKelime('خَلَقَ', 'halaka', 'yarattı'),
  SozlukKelime('رَزَقَ', 'razeka', 'rızık verdi'),
  SozlukKelime('نَصَرَ', 'nasara', 'yardım etti'),
  SozlukKelime('مَاتَ', 'mâte', 'öldü'),
  SozlukKelime('وُلِدَ', 'vülide', 'doğdu'),
  SozlukKelime('عَاشَ', 'âşe', 'yaşadı'),

  // ── Sıfatlar ──
  SozlukKelime('كَبِير', 'kebîr', 'büyük'),
  SozlukKelime('صَغِير', 'sağîr', 'küçük'),
  SozlukKelime('طَوِيل', 'tavîl', 'uzun'),
  SozlukKelime('قَصِير', 'kasîr', 'kısa'),
  SozlukKelime('جَدِيد', 'cedîd', 'yeni'),
  SozlukKelime('قَدِيم', 'kadîm', 'eski'),
  SozlukKelime('جَمِيل', 'cemîl', 'güzel'),
  SozlukKelime('قَبِيح', 'kabîh', 'çirkin'),
  SozlukKelime('سَهْل', 'sehl', 'kolay'),
  SozlukKelime('صَعْب', 'sa\'b', 'zor'),
  SozlukKelime('سَرِيع', 'serî', 'hızlı'),
  SozlukKelime('بَطِيء', 'batî', 'yavaş'),
  SozlukKelime('قَوِيّ', 'kavî', 'güçlü'),
  SozlukKelime('ضَعِيف', 'zaîf', 'zayıf'),
  SozlukKelime('غَنِيّ', 'ğanî', 'zengin'),
  SozlukKelime('فَقِير', 'fakîr', 'fakir'),
  SozlukKelime('سَعِيد', 'saîd', 'mutlu'),
  SozlukKelime('حَزِين', 'hazîn', 'üzgün'),
  SozlukKelime('حَارّ', 'hârr', 'sıcak'),
  SozlukKelime('بَارِد', 'bârid', 'soğuk'),
  SozlukKelime('نَظِيف', 'nazîf', 'temiz'),
  SozlukKelime('وَسِخ', 'vesih', 'kirli'),
  SozlukKelime('قَرِيب', 'karîb', 'yakın'),
  SozlukKelime('بَعِيد', 'baîd', 'uzak'),
  SozlukKelime('كَثِير', 'kesîr', 'çok'),
  SozlukKelime('قَلِيل', 'kalîl', 'az'),
  SozlukKelime('ثَقِيل', 'sakîl', 'ağır'),
  SozlukKelime('خَفِيف', 'hafîf', 'hafif'),
  SozlukKelime('مُمْتَلِئ', 'mümteli', 'dolu'),
  SozlukKelime('فَارِغ', 'fâriğ', 'boş'),
  SozlukKelime('صَحِيح', 'sahîh', 'doğru, sağlam'),
  SozlukKelime('خَطَأ', 'hata', 'yanlış, hata'),
  SozlukKelime('مَرِيض', 'marîd', 'hasta'),
  SozlukKelime('سَلِيم', 'selîm', 'sağlıklı, sağlam'),
  SozlukKelime('عَالٍ', 'âlî', 'yüksek'),
  SozlukKelime('مُنْخَفِض', 'münhafid', 'alçak'),
  SozlukKelime('وَاسِع', 'vâsi', 'geniş'),
  SozlukKelime('ضَيِّق', 'dayyik', 'dar'),

  // ── Yiyecek & içecek ──
  SozlukKelime('فَاكِهَة', 'fâkihe', 'meyve'),
  SozlukKelime('خُضَار', 'hudâr', 'sebze'),
  SozlukKelime('تُفَّاح', 'tüffâh', 'elma'),
  SozlukKelime('عِنَب', 'ineb', 'üzüm'),
  SozlukKelime('تَمْر', 'temr', 'hurma'),
  SozlukKelime('تِين', 'tîn', 'incir'),
  SozlukKelime('زَيْتُون', 'zeytûn', 'zeytin'),
  SozlukKelime('رُمَّان', 'rummân', 'nar'),
  SozlukKelime('بُرْتُقَال', 'burtukâl', 'portakal'),
  SozlukKelime('مَوْز', 'mevz', 'muz'),
  SozlukKelime('بِطِّيخ', 'bittîh', 'karpuz'),
  SozlukKelime('جَزَر', 'cezer', 'havuç'),
  SozlukKelime('بَصَل', 'basal', 'soğan'),
  SozlukKelime('ثُوم', 'sûm', 'sarımsak'),
  SozlukKelime('بَطَاطِس', 'batâtis', 'patates'),
  SozlukKelime('طَمَاطِم', 'tamâtim', 'domates'),
  SozlukKelime('أَرُزّ', 'eruzz', 'pirinç'),
  SozlukKelime('قَمْح', 'kamh', 'buğday'),
  SozlukKelime('سُكَّر', 'sükker', 'şeker'),
  SozlukKelime('مِلْح', 'milh', 'tuz'),
  SozlukKelime('زَيْت', 'zeyt', 'yağ (zeytinyağı)'),
  SozlukKelime('بَيْض', 'beyd', 'yumurta'),
  SozlukKelime('جُبْن', 'cübn', 'peynir'),
  SozlukKelime('شَاي', 'şây', 'çay'),
  SozlukKelime('قَهْوَة', 'kahve', 'kahve'),
  SozlukKelime('عَصِير', 'asîr', 'meyve suyu'),

  // ── Hayvanlar ──
  SozlukKelime('حَيَوَان', 'hayevân', 'hayvan'),
  SozlukKelime('قِطّ', 'kıtt', 'kedi'),
  SozlukKelime('كَلْب', 'kelb', 'köpek'),
  SozlukKelime('حِصَان', 'hisân', 'at'),
  SozlukKelime('جَمَل', 'cemel', 'deve'),
  SozlukKelime('بَقَرَة', 'bakara', 'inek'),
  SozlukKelime('خَرُوف', 'harûf', 'kuzu'),
  SozlukKelime('غَنَم', 'ğanem', 'koyun'),
  SozlukKelime('مَاعِز', 'mâiz', 'keçi'),
  SozlukKelime('دَجَاجَة', 'decâce', 'tavuk'),
  SozlukKelime('دِيك', 'dîk', 'horoz'),
  SozlukKelime('بَطّ', 'batt', 'ördek'),
  SozlukKelime('نَحْلَة', 'nahle', 'arı'),
  SozlukKelime('نَمْلَة', 'nemle', 'karınca'),
  SozlukKelime('فَرَاشَة', 'ferâşe', 'kelebek'),
  SozlukKelime('عُصْفُور', 'usfûr', 'serçe'),
  SozlukKelime('نَسْر', 'nesr', 'kartal'),
  SozlukKelime('ذِئْب', 'zi\'b', 'kurt'),
  SozlukKelime('ثَعْلَب', 'sa\'leb', 'tilki'),
  SozlukKelime('فِيل', 'fîl', 'fil'),
  SozlukKelime('قِرْد', 'kırd', 'maymun'),
  SozlukKelime('أَرْنَب', 'erneb', 'tavşan'),
  SozlukKelime('فَأْر', 'fe\'r', 'fare'),
  SozlukKelime('ثُعْبَان', 'su\'bân', 'yılan'),
  SozlukKelime('سَمَك', 'semek', 'balık'),

  // ── Beden (ek) ──
  SozlukKelime('جِسْم', 'cism', 'beden'),
  SozlukKelime('شَعْر', 'şa\'r', 'saç'),
  SozlukKelime('جَبِين', 'cebîn', 'alın'),
  SozlukKelime('خَدّ', 'hadd', 'yanak'),
  SozlukKelime('سِنّ', 'sinn', 'diş'),
  SozlukKelime('شَفَة', 'şefe', 'dudak'),
  SozlukKelime('رَقَبَة', 'rakabe', 'boyun'),
  SozlukKelime('كَتِف', 'ketif', 'omuz'),
  SozlukKelime('ذِرَاع', 'zirâ', 'kol'),
  SozlukKelime('إِصْبَع', 'ısba', 'parmak'),
  SozlukKelime('ظَهْر', 'zahr', 'sırt'),
  SozlukKelime('بَطْن', 'batn', 'karın'),
  SozlukKelime('صَدْر', 'sadr', 'göğüs'),
  SozlukKelime('رُكْبَة', 'rukbe', 'diz'),
  SozlukKelime('عَظْم', 'azm', 'kemik'),
  SozlukKelime('جِلْد', 'cild', 'deri'),

  // ── Ev & eşya ──
  SozlukKelime('غُرْفَة', 'gurfe', 'oda'),
  SozlukKelime('مَطْبَخ', 'matbah', 'mutfak'),
  SozlukKelime('نَافِذَة', 'nâfize', 'pencere'),
  SozlukKelime('سَقْف', 'sakf', 'tavan'),
  SozlukKelime('جِدَار', 'cidâr', 'duvar'),
  SozlukKelime('أَرْضِيَّة', 'ardıyye', 'zemin'),
  SozlukKelime('سَرِير', 'serîr', 'yatak'),
  SozlukKelime('كُرْسِيّ', 'kürsî', 'sandalye'),
  SozlukKelime('طَاوِلَة', 'tâvile', 'masa'),
  SozlukKelime('مِفْتَاح', 'miftâh', 'anahtar'),
  SozlukKelime('مِصْبَاح', 'misbâh', 'lamba'),
  SozlukKelime('سَاعَة', 'sâa', 'saat (nesne)'),
  SozlukKelime('مِرْآة', 'mir\'ât', 'ayna'),
  SozlukKelime('صَحْن', 'sahn', 'tabak'),
  SozlukKelime('كَأْس', 'ke\'s', 'bardak'),
  SozlukKelime('مِلْعَقَة', 'mil\'aka', 'kaşık'),
  SozlukKelime('سِكِّين', 'sikkîn', 'bıçak'),
  SozlukKelime('قَلَم رَصَاص', 'kalem rasâs', 'kurşun kalem'),
  SozlukKelime('وَرَق', 'varak', 'kâğıt'),
  SozlukKelime('حَقِيبَة', 'hakîbe', 'çanta'),

  // ── Şehir & yer ──
  SozlukKelime('قَرْيَة', 'karye', 'köy'),
  SozlukKelime('شَارِع', 'şâri', 'cadde'),
  SozlukKelime('مَدْرَسَة', 'medrese', 'okul'),
  SozlukKelime('جَامِعَة', 'câmia', 'üniversite'),
  SozlukKelime('مُسْتَشْفَى', 'müstaşfâ', 'hastane'),
  SozlukKelime('مَكْتَبَة', 'mektebe', 'kütüphane'),
  SozlukKelime('مَطْعَم', 'mat\'am', 'lokanta'),
  SozlukKelime('فُنْدُق', 'fündük', 'otel'),
  SozlukKelime('مَطَار', 'matâr', 'havaalanı'),
  SozlukKelime('مَحَطَّة', 'mahatta', 'istasyon'),
  SozlukKelime('حَدِيقَة', 'hadîka', 'bahçe, park'),
  SozlukKelime('مَيْدَان', 'meydân', 'meydan'),
  SozlukKelime('جِسْر', 'cisr', 'köprü'),
  SozlukKelime('بَلَد', 'beled', 'ülke, belde'),
  SozlukKelime('عَاصِمَة', 'âsıme', 'başkent'),
  SozlukKelime('حُدُود', 'hudûd', 'sınır'),
  SozlukKelime('صَحْرَاء', 'sahrâ', 'çöl'),
  SozlukKelime('غَابَة', 'ğâbe', 'orman'),
  SozlukKelime('وَادٍ', 'vâdî', 'vadi'),
  SozlukKelime('كَهْف', 'kehf', 'mağara'),

  // ── Ulaşım ──
  SozlukKelime('سَيَّارَة', 'seyyâre', 'araba'),
  SozlukKelime('حَافِلَة', 'hâfile', 'otobüs'),
  SozlukKelime('قِطَار', 'kıtâr', 'tren'),
  SozlukKelime('طَائِرَة', 'tâire', 'uçak'),
  SozlukKelime('سَفِينَة', 'sefîne', 'gemi'),
  SozlukKelime('دَرَّاجَة', 'derrâce', 'bisiklet'),
  SozlukKelime('قَارِب', 'kârib', 'kayık'),

  // ── Meslekler ──
  SozlukKelime('مُعَلِّم', 'muallim', 'öğretmen'),
  SozlukKelime('طَالِب', 'tâlib', 'öğrenci'),
  SozlukKelime('طَبِيب', 'tabîb', 'doktor'),
  SozlukKelime('مُهَنْدِس', 'mühendis', 'mühendis'),
  SozlukKelime('تَاجِر', 'tâcir', 'tüccar'),
  SozlukKelime('فَلَّاح', 'fellâh', 'çiftçi'),
  SozlukKelime('نَجَّار', 'neccâr', 'marangoz'),
  SozlukKelime('خَبَّاز', 'habbâz', 'fırıncı'),
  SozlukKelime('طَبَّاخ', 'tabbâh', 'aşçı'),
  SozlukKelime('شُرْطِيّ', 'şurtî', 'polis'),
  SozlukKelime('قَاضٍ', 'kâdî', 'hâkim'),
  SozlukKelime('كَاتِب', 'kâtib', 'yazar, kâtip'),
  SozlukKelime('إِمَام', 'imâm', 'imam'),
  SozlukKelime('مُؤَذِّن', 'müezzin', 'müezzin'),

  // ── Dini terimler (ek) ──
  SozlukKelime('تَوْحِيد', 'tevhîd', 'Allah\'ın birliği'),
  SozlukKelime('عِبَادَة', 'ibâde', 'ibadet'),
  SozlukKelime('طَهَارَة', 'tahâre', 'temizlik (dini)'),
  SozlukKelime('وُضُوء', 'vudû', 'abdest'),
  SozlukKelime('غُسْل', 'gusl', 'gusül'),
  SozlukKelime('أَذَان', 'ezân', 'ezan'),
  SozlukKelime('إِقَامَة', 'ikâme', 'kamet'),
  SozlukKelime('رَكْعَة', 'rek\'a', 'rekât'),
  SozlukKelime('سَجْدَة', 'secde', 'secde'),
  SozlukKelime('رُكُوع', 'rükû', 'rükû'),
  SozlukKelime('قِيَام', 'kıyâm', 'ayakta duruş'),
  SozlukKelime('نِيَّة', 'niyye', 'niyet'),
  SozlukKelime('فَرْض', 'fard', 'farz'),
  SozlukKelime('سُنَّة', 'sünne', 'sünnet'),
  SozlukKelime('حَدِيث', 'hadîs', 'hadis'),
  SozlukKelime('تَفْسِير', 'tefsîr', 'tefsir'),
  SozlukKelime('شَرِيعَة', 'şerîa', 'şeriat'),
  SozlukKelime('فِقْه', 'fıkh', 'fıkıh'),
  SozlukKelime('حَلَال', 'helâl', 'helal'),
  SozlukKelime('ذَنْب', 'zenb', 'günah'),
  SozlukKelime('ثَوَاب', 'sevâb', 'sevap'),
  SozlukKelime('جَهَنَّم', 'cehennem', 'cehennem'),
  SozlukKelime('قِيَامَة', 'kıyâme', 'kıyamet'),
  SozlukKelime('مِيزَان', 'mîzân', 'terazi (mahşer)'),
  SozlukKelime('صِرَاط', 'sırât', 'sırat'),
  SozlukKelime('شَهِيد', 'şehîd', 'şehit'),
  SozlukKelime('شَفَاعَة', 'şefâa', 'şefaat'),

  // ── Soyut kavramlar (ek) ──
  SozlukKelime('حَيَاة', 'hayât', 'hayat'),
  SozlukKelime('مَوْت', 'mevt', 'ölüm'),
  SozlukKelime('حُرِّيَّة', 'hürriyye', 'özgürlük'),
  SozlukKelime('عَدَالَة', 'adâle', 'adalet'),
  SozlukKelime('ظُلْم', 'zulm', 'zulüm'),
  SozlukKelime('حَقِيقَة', 'hakîka', 'gerçek, hakikat'),
  SozlukKelime('كَذِب', 'kizb', 'yalan'),
  SozlukKelime('وَعْد', 'va\'d', 'söz, vaat'),
  SozlukKelime('عَهْد', 'ahd', 'ahit, sözleşme'),
  SozlukKelime('أَمَانَة', 'emâne', 'emanet'),
  SozlukKelime('خِيَانَة', 'hıyâne', 'ihanet'),
  SozlukKelime('كَرَامَة', 'kerâme', 'onur, kerâmet'),
  SozlukKelime('تَوَاضُع', 'tevâdu', 'alçakgönüllülük'),
  SozlukKelime('كِبْر', 'kibr', 'kibir'),
  SozlukKelime('غَيْرَة', 'ğayre', 'kıskançlık, gayret'),
  SozlukKelime('طُمَأْنِينَة', 'tuma\'nîne', 'huzur, sükûnet'),
  SozlukKelime('قَلَق', 'kalak', 'endişe'),
  SozlukKelime('يَقِين', 'yakîn', 'kesin bilgi'),
  SozlukKelime('شَكّ', 'şekk', 'şüphe'),
  SozlukKelime('عَقْل', 'akl', 'akıl'),
  SozlukKelime('فِكْر', 'fikr', 'düşünce'),
  SozlukKelime('خَيَال', 'hayâl', 'hayal'),
  SozlukKelime('ذَاكِرَة', 'zâkire', 'hafıza'),
  SozlukKelime('لُغَة', 'luğa', 'dil (lisan)'),
  SozlukKelime('مَعْنَى', 'ma\'nâ', 'anlam'),
  SozlukKelime('سُؤَال', 'suâl', 'soru'),
  SozlukKelime('فِعْل', 'fi\'l', 'fiil, eylem'),
  SozlukKelime('عَادَة', 'âde', 'alışkanlık, âdet'),

  // ── Zaman (ek) ──
  SozlukKelime('لَحْظَة', 'lahza', 'an'),
  SozlukKelime('دَقِيقَة', 'dakîka', 'dakika'),
  SozlukKelime('ثَانِيَة', 'sâniye', 'saniye'),
  SozlukKelime('فَجْر', 'fecr', 'şafak, tan'),
  SozlukKelime('ظُهْر', 'zuhr', 'öğle'),
  SozlukKelime('عَصْر', 'asr', 'ikindi'),
  SozlukKelime('مَغْرِب', 'mağrib', 'akşam (batı)'),
  SozlukKelime('عِشَاء', 'işâ', 'yatsı'),
  SozlukKelime('رَبِيع', 'rabî', 'ilkbahar'),
  SozlukKelime('صَيْف', 'sayf', 'yaz'),
  SozlukKelime('خَرِيف', 'harîf', 'sonbahar'),
  SozlukKelime('شِتَاء', 'şitâ', 'kış'),

  // ── Doğa (ek) ──
  SozlukKelime('سَحَاب', 'sehâb', 'bulut'),
  SozlukKelime('بَرْق', 'bark', 'şimşek'),
  SozlukKelime('رَعْد', 'ra\'d', 'gök gürültüsü'),
  SozlukKelime('ثَلْج', 'selc', 'kar'),
  SozlukKelime('جَلِيد', 'celîd', 'buz'),
  SozlukKelime('ضَبَاب', 'dabâb', 'sis'),
  SozlukKelime('قَوْس قُزَح', 'kavs kuzah', 'gökkuşağı'),
  SozlukKelime('ظِلّ', 'zıll', 'gölge'),
  SozlukKelime('نُور', 'nûr', 'ışık'),
  SozlukKelime('دُخَان', 'duhân', 'duman'),
  SozlukKelime('رَمْل', 'raml', 'kum'),
  SozlukKelime('طِين', 'tîn', 'çamur'),
  SozlukKelime('عُشْب', 'uşb', 'çimen'),
  SozlukKelime('غُصْن', 'ğusn', 'dal'),
  SozlukKelime('وَرَقَة', 'varaka', 'yaprak'),
  SozlukKelime('جَذْر', 'cezr', 'kök'),
  SozlukKelime('ثَمَرَة', 'semere', 'meyve, ürün'),
  SozlukKelime('بَذْرَة', 'bezre', 'tohum'),

  // ── Yön & konum ──
  SozlukKelime('يَمِين', 'yemîn', 'sağ'),
  SozlukKelime('يَسَار', 'yesâr', 'sol'),
  SozlukKelime('أَمَام', 'emâm', 'ön'),
  SozlukKelime('خَلْف', 'half', 'arka'),
  SozlukKelime('فَوْق', 'fevk', 'üst'),
  SozlukKelime('تَحْت', 'taht', 'alt'),
  SozlukKelime('دَاخِل', 'dâhil', 'iç'),
  SozlukKelime('خَارِج', 'hâric', 'dış'),
  SozlukKelime('شَمَال', 'şemâl', 'kuzey'),
  SozlukKelime('جَنُوب', 'cenûb', 'güney'),
  SozlukKelime('شَرْق', 'şark', 'doğu'),
  SozlukKelime('غَرْب', 'ğarb', 'batı'),
  SozlukKelime('وَسَط', 'vasat', 'orta'),
  SozlukKelime('بَيْن', 'beyn', 'arasında'),

  // ── Sayılar (ek) ──
  SozlukKelime('أَحَد عَشَر', 'ehade aşer', 'on bir (11)'),
  SozlukKelime('عِشْرُون', 'işrûn', 'yirmi (20)'),
  SozlukKelime('ثَلَاثُون', 'selâsûn', 'otuz (30)'),
  SozlukKelime('أَرْبَعُون', 'erbaûn', 'kırk (40)'),
  SozlukKelime('خَمْسُون', 'hamsûn', 'elli (50)'),
  SozlukKelime('نِصْف', 'nısf', 'yarım'),
  SozlukKelime('رُبْع', 'rub\'', 'çeyrek'),
  SozlukKelime('أَوَّل', 'evvel', 'birinci, ilk'),
  SozlukKelime('آخِر', 'âhir', 'son'),

  // ── Aile & insan (ek) ──
  SozlukKelime('جَدّ', 'cedd', 'dede'),
  SozlukKelime('جَدَّة', 'cedde', 'nine'),
  SozlukKelime('عَمّ', 'amm', 'amca'),
  SozlukKelime('خَال', 'hâl', 'dayı'),
  SozlukKelime('عَمَّة', 'amme', 'hala'),
  SozlukKelime('خَالَة', 'hâle', 'teyze'),
  SozlukKelime('حَفِيد', 'hafîd', 'torun'),
  SozlukKelime('طِفْل', 'tıfl', 'bebek, çocuk'),
  SozlukKelime('شَابّ', 'şâbb', 'genç'),
  SozlukKelime('شَيْخ', 'şeyh', 'yaşlı, şeyh'),
  SozlukKelime('عَرُوس', 'arûs', 'gelin'),
  SozlukKelime('أُسْرَة', 'üsra', 'aile'),
  SozlukKelime('شَعْب', 'şa\'b', 'halk'),
  SozlukKelime('قَوْم', 'kavm', 'kavim, topluluk'),

  // ── Fiil/edat & yaygın kelimeler ──
  SozlukKelime('نَعَم', 'neam', 'evet'),
  SozlukKelime('لَا', 'lâ', 'hayır'),
  SozlukKelime('رُبَّمَا', 'rubbemâ', 'belki'),
  SozlukKelime('دَائِمًا', 'dâimen', 'her zaman'),
  SozlukKelime('أَحْيَانًا', 'ahyânen', 'bazen'),
  SozlukKelime('هُنَا', 'hünâ', 'burada'),
  SozlukKelime('هُنَاك', 'hünâk', 'orada'),
  SozlukKelime('الْآن', 'el-ân', 'şimdi'),
  SozlukKelime('كَيْفَ', 'keyfe', 'nasıl'),
  SozlukKelime('لِمَاذَا', 'limâzâ', 'neden'),
  SozlukKelime('مَتَى', 'metâ', 'ne zaman'),
  SozlukKelime('أَيْنَ', 'eyne', 'nerede'),
  SozlukKelime('مَنْ', 'men', 'kim'),
  SozlukKelime('مَا', 'mâ', 'ne'),
  SozlukKelime('كَمْ', 'kem', 'kaç, ne kadar'),
  SozlukKelime('شُكْرًا', 'şükran', 'teşekkürler'),
  SozlukKelime('عَفْوًا', 'afven', 'affedersiniz, rica ederim'),
  SozlukKelime('مَرْحَبًا', 'merhaben', 'merhaba'),
  SozlukKelime('وَدَاعًا', 'vedâan', 'hoşça kal'),
];
