// Sosyal — dini günler için kısa kutlama mesajları, şiirler ve dualar.
// Her mesaj paylaşılabilir bir görsel karta dönüştürülebilir.

class SosyalVesile {
  final String id, baslik, altBaslik;
  final List<String> mesajlar;
  const SosyalVesile(this.id, this.baslik, this.altBaslik, this.mesajlar);
}

const List<SosyalVesile> kSosyalVesileler = [
  SosyalVesile('ramazan', 'Ramazan Bayramı', 'Bayram tebrikleri', [
    'Otuz günün sabrı bir sabaha döküldü; gönüller bir, dualar bir oldu. Ramazan Bayramınız mübarek, sofranız bereketli, kalbiniz huzur dolu olsun.',
    'Orucun rahmeti, bayramın neşesine karıştı. Yüzünüz hep gülsün, sevginiz hiç eksilmesin. İyi bayramlar.',
    'Bu mübarek sabahta dargınlıklar erisin, gönüller barışsın, eviniz bir çocuğun kahkahası kadar aydınlansın. Bayramınız kutlu olsun.',
    'Nice bayramlara; sevdiklerinizle aynı sofrada, sağlık ve huzur içinde erişmeniz duasıyla. Ramazan Bayramınız mübarek olsun.',
    'Ellerimiz açıldı, gönlümüz arındı, bayram geldi. Rabbim tuttuğunuz oruçları kabul, ettiğiniz duaları makbul eylesin.',
    'Bayram, kırgınlıkları bir kenara bırakıp yeniden sarılabilmektir. Kucaklaşmanız muhabbetle, sofranız bereketle dolsun.',
    'Ramazanın ardından gelen bu tatlı sabah, ömrünüze huzur, evinize bereket, kalbinize iman ferahlığı getirsin.',
    'Şeker tadında günler, dua tadında geceler dilerim. Bayramınız mübarek, gönlünüz mahzun olmasın.',
    'Bir ay boyunca yeşeren manevi bahar, bayramla meyveye dursun. Sağlıcakla, sevgiyle, huzurla nice bayramlara.',
    'Gönlünüzdeki en güzel duayı Rabbim yerde bırakmasın. Ramazan Bayramınız kutlu, yolunuz aydınlık olsun.',
  ]),
  SosyalVesile('kurban', 'Kurban Bayramı', 'Bayram tebrikleri', [
    'Teslimiyetin ve fedakârlığın bayramı… Kurban Bayramınız mübarek olsun, niyetleriniz halis, kurbanlarınız kabul olsun.',
    'Bu bayram, paylaştıkça çoğalan bir bereket getirsin. Gönlünüz hep tok, sofranız komşularla dolu olsun. İyi bayramlar.',
    'İbrahimî bir teslimiyetle, İsmailce bir sadakatle… Kurban Bayramınız kutlu, kurbanlarınız makbul olsun.',
    'Sevgi paylaşıldıkça güzelleşir. Bayramınız bereketli, elleriniz veren el, gönlünüz tok olsun.',
    'Kurban, en sevdiğini Rabbine adayabilmektir. Bu bayram gönlünüzden geçen hayırlar gerçek olsun, dualarınız arşa yükselsin.',
    'Bir lokması bin dua olan bayramda; yetimin yüzü gülsün, yoksulun sofrası şenlensin, gönlünüz huzur bulsun.',
    'Rabbim adaklarınızı kabul, hayırlarınızı daim, sevdiklerinizi başınızdan eksik etmesin. Kurban Bayramınız mübarek olsun.',
    'Fedakârlık büyüdükçe bereket büyür. Bu mübarek günlerde eviniz huzurla, gönlünüz şükürle dolsun.',
    'Paylaşmanın en güzel adı bayram… Kurbanınız kabul, bayramınız kutlu, ömrünüz bereketli olsun.',
    'Uzaktaki gönüller bugün birbirine daha yakın. Bayramınızı canı gönülden kutlar, hayırlı bayramlar dilerim.',
  ]),
  SosyalVesile('regaip', 'Regaip Kandili', 'Kandil tebrikleri', [
    'Rahmet kapılarının ardına dek açıldığı bu gecede, dualarınız kabul, gönlünüz nurla dolsun. Regaip Kandiliniz mübarek olsun.',
    'Üç ayların müjdecisi Regaip\'te; niyetleriniz hayır, tövbeleriniz makbul, kalbiniz huzur bulsun.',
    'Bu mübarek gecede edilen dualar geri çevrilmez derler. Kandiliniz mübarek, avucunuz boş dönmesin.',
    'Semaların rahmetle donandığı bu gecede, gönlünüzden geçen en güzel dilek gerçek olsun. Hayırlı Regaip Kandilleri.',
    'Receb ayının ilk incisi Regaip… Bu gece kalbiniz arınsın, defteriniz sevapla, yüzünüz nurla dolsun.',
    'Gecenin sessizliğinde yükselen dualar en makbul olanıdır. Kandiliniz mübarek, dualarınız kabul olsun.',
    'Rabbim bu mübarek gecenin hürmetine dertlerinize derman, dualarınıza icabet nasip etsin. Hayırlı kandiller.',
    'Üç ayların kapısı Regaip ile aralandı. Manevi yolculuğunuz bereketli, gönlünüz huzurlu olsun.',
    'Bu gece göz yaşıyla edilen tövbeler boşa gitmez. Kandiliniz mübarek, kalbiniz pak olsun.',
    'Regaip, rağbetin ve umudun gecesidir. Umutlarınız yeşersin, dualarınız yerini bulsun. Hayırlı kandiller.',
  ]),
  SosyalVesile('mirac', 'Mirac Kandili', 'Kandil tebrikleri', [
    'Göklerin kapısının aralandığı bu mübarek gecede, dualarınız arşa yükselsin. Mirac Kandiliniz mübarek olsun.',
    'Mirac, kulluğun en yüce yolculuğudur. Bu gece gönlünüz semaya açılsın, duanız kabul olsun.',
    'Namazın bir hediye olarak gönderildiği bu gecede; secdeleriniz huzur, dualarınız nur olsun. Hayırlı kandiller.',
    'Bir kulun Rabbine en yakın olduğu gece Mirac\'tır. Gönlünüz o yakınlığın huzuruyla dolsun. Kandiliniz mübarek olsun.',
    'Bu gece yeryüzünden göklere bir merdiven kurulur. Dualarınız o merdivenden çıksın, boş dönmesin.',
    'Mirac, imanın kanatlanıp semaya yükselmesidir. Kalbiniz o kanatlarla hafiflesin, yükünüz azalsın. Hayırlı kandiller.',
    'Rabbim bu mübarek gecenin sırrına erenlerden, dualarına icabet edilenlerden eylesin. Mirac Kandiliniz kutlu olsun.',
    'Sınırların aşıldığı, perdelerin kalktığı bu gecede; gönlünüzdeki en gizli duayı Rabbim duysun ve kabul etsin.',
    'Beş vakit namaz, Mirac gecesinin bize armağanıdır. Secdeleriniz daim, huzurunuz kalıcı olsun. Hayırlı kandiller.',
    'Bu mübarek gecede kalbiniz nurla, eviniz huzurla, ömrünüz bereketle dolsun. Mirac Kandiliniz mübarek olsun.',
  ]),
  SosyalVesile('berat', 'Berat Kandili', 'Kandil tebrikleri', [
    'Affın ve beraatin gecesi… Geçmiş günahlarınız bağışlansın, defteriniz nurla dolsun. Berat Kandiliniz mübarek olsun.',
    'Bu gece rahmet sağanak sağanak yağar. Tövbeleriniz kabul, kalbiniz pak, alnınız ak olsun.',
    'Berat, yeniden başlayabilmektir. Gönlünüz arınsın, yolunuz aydınlansın, yükünüz hafiflesin. Hayırlı kandiller.',
    'Kaderin yazıldığı, amellerin arz edildiği bu gecede; defterinize hayır, ömrünüze bereket yazılsın.',
    'Bu mübarek gecede Rabbim beratınızı elinize versin, günahlarınızı bağışlasın, gönlünüzü ferahlatsın.',
    'Berat gecesi, affedilmenin en yakın olduğu andır. Tövbe kapısı ardına dek açık; gönlünüz o kapıdan geçsin.',
    'Şaban\'ın ortasında yükselen bu nur, kalbinizdeki karanlıkları dağıtsın. Kandiliniz mübarek, yüzünüz nurlu olsun.',
    'Rabbim bu gecenin hürmetine sizi affettiklerinden, sevdiklerinden ve rahmetiyle kucakladıklarından eylesin.',
    'Geçmişin yükünü bırakıp tertemiz bir sayfa açmanın vaktidir. Gönlünüz hafiflesin, umudunuz tazelensin.',
    'Bu mübarek gecede döktüğünüz her gözyaşı, açtığınız her el makbul olsun. Berat Kandiliniz kutlu olsun.',
  ]),
  SosyalVesile('kadir', 'Kadir Gecesi', 'Bin aydan hayırlı gece', [
    'Bin aydan hayırlı bu gecede, tek bir duanız bile ömrünüzü aydınlatsın. Kadir Geceniz mübarek olsun.',
    'Meleklerin yeryüzüne indiği bu mübarek gecede; gönlünüz huzurla, defteriniz sevapla dolsun.',
    'Kadir Gecesi\'nin feyzi üzerinize olsun; dualarınız kabul, kalbiniz nur ile dolu olsun.',
    'Bir ömre bedel bu gecede; her secdeniz bin secde, her duanız bin dua değerinde olsun.',
    'Kur\'an\'ın yeryüzüne indiği gece Kadir\'dir. Kalbiniz o nurla aydınlansın, yolunuz hiç kararmasın.',
    'Bu gece sabaha kadar rahmet iner. Uyanık kalan gönüllere selam olsun; dualarınız arşa ulaşsın.',
    'Bin ayı bir geceye sığdıran Rabbim, bu gecenin bereketini ömrünüze yaysın. Kadir Geceniz mübarek olsun.',
    'Kadir Gecesi, kadrin ve kıymetin gecesidir. Kıymetli dualarınız kıymet bulsun, boş dönmesin.',
    'Bu mübarek gecede edilen bir tövbe, bir ömrü temize çeker. Gönlünüz arınsın, defteriniz aklansın.',
    'Selametle dolu, esenlikle biten bir gece dilerim. Kadir Geceniz mübarek, dualarınız makbul olsun.',
  ]),
  SosyalVesile('mevlid', 'Mevlid Kandili', 'Peygamberimizin doğumu', [
    'Âlemlere rahmet olarak gönderilen Sevgili Peygamberimizin dünyayı şereflendirdiği bu gece kutlu olsun. Mevlid Kandiliniz mübarek olsun.',
    'O\'nun (s.a.v.) yolu sevgi, merhamet ve barıştır. Bu mübarek gecede gönlünüz O\'nun sevgisiyle dolsun.',
    'Bir gül doğdu âleme, kâinat kokusuyla ıtırlandı. Mevlid Kandilinde salavatlarınız eksik olmasın. Hayırlı kandiller.',
    'Karanlığa doğan bir güneşti O. Yüreğiniz O\'nun ahlakıyla aydınlansın, yolunuz sünnetiyle şenlensin.',
    'Bu gece âlemlerin efendisi doğdu; gökler sevindi, yer güldü. Sevgisi kalbinizden hiç eksilmesin. Mevlid Kandiliniz mübarek olsun.',
    'O\'na bir salavat, gönle bin ferahlıktır. Bu mübarek gecede diliniz salavatla, kalbiniz muhabbetle dolsun.',
    'Rahmet Peygamberi\'nin doğduğu bu gecede; şefaatine nail olmak, izinden gitmek nasip olsun. Hayırlı kandiller.',
    'Merhametin, vefanın ve sevginin timsali O\'ydu. Bu gece O\'nun (s.a.v.) sevgisi eviniz ve gönlünüz için nur olsun.',
    'Gönül tahtına bir sultan doğdu bu gece. Sevdası kalbinize taht kursun, sünneti yolunuza ışık olsun.',
    'Mevlid Kandiliniz mübarek olsun; Peygamber sevgisi ailenizden, salavat dilinizden eksik olmasın.',
  ]),
  SosyalVesile('cuma', 'Cuma Mesajları', 'Hayırlı cumalar', [
    'Cuma, gönüllerin buluştuğu, duaların kabul olduğu gündür. Hayırlı cumalar, bereketli günler.',
    'Bu mübarek Cuma gününde dualarınız kabul, kalbiniz huzur, sofranız bereket dolu olsun.',
    'Salât ü selamların arşa yükseldiği bu günde, gönlünüz nurla dolsun. Hayırlı cumalar.',
    'Cumanız mübarek olsun; dertleriniz derman, dualarınız makbul, yüzünüz hep gülsün.',
    'Haftanın bayramı Cuma… Gönlünüzden geçen hayırlı dilekler bu mübarek günün hürmetine kabul olsun.',
    'Bir Cuma daha rahmetle doğdu. Kalbiniz ferah, rızkınız bol, gönlünüz huzurlu olsun. Hayırlı cumalar.',
    'Salavatların gökyüzünü doldurduğu bu günde; Rabbim dualarınızı yerde koymasın. Cumanız mübarek olsun.',
    'Cuma, gönlün paslarını silen bir rahmet günüdür. Kalbiniz arınsın, yükünüz hafiflesin. Hayırlı cumalar.',
    'Bu mübarek günde ettiğiniz dua sizden önce arşa varsın. Rızkınıza bereket, ömrünüze huzur dilerim.',
    'Rahmetin sağanak yağdığı Cuma vaktinde; sağlık, huzur ve bereket kapınızı çalsın. Hayırlı cumalar.',
  ]),
  SosyalVesile('asure', 'Aşure / Muharrem', 'Muharrem ayı', [
    'Bereketin ve paylaşmanın sembolü aşure gibi, hayatınız da tatlı ve bol olsun. Hayırlı Muharremler.',
    'Muharrem ayının rahmeti üzerinize olsun; gönlünüz tok, sofranız komşularla paylaşıldıkça bereketli olsun.',
    'Bir kazanda kırk bereket kaynar aşurede… Gönlünüz de o bereketle dolsun, komşuluğunuz tatlansın. Hayırlı Muharremler.',
    'Hicri yılın ilk ayı Muharrem hayırlar getirsin. Geçen yılın yükü hafiflesin, yeni yıl umutla açılsın.',
    'Paylaştıkça çoğalan bir tas aşure gibi; sevginiz bölündükçe artsın, bereketiniz eksilmesin.',
    'Muharrem\'in hüznü kalbinizi olgunlaştırsın, aşurenin tatlılığı ömrünüze karışsın. Hayırlı Muharremler.',
    'Bu mübarek ayda ettiğiniz oruç, döktüğünüz dua, dağıttığınız aşure Rabbim katında makbul olsun.',
    'Kerbelâ\'nın hüznünü, aşurenin bereketini taşıyan Muharrem\'iniz hayırlı olsun. Gönlünüz huzur bulsun.',
  ]),
  SosyalVesile('uc_aylar', 'Üç Aylar & Genel', 'Manevi mevsim', [
    'Rahmet, mağfiret ve bereket mevsimi üç aylar hayırlı olsun. Gönüllerimiz manevi bir baharla dirilsin.',
    'Receb, Şaban ve Ramazan… Bu manevi yolculukta kalbiniz huzur, duanız kabul olsun. Hayırlı üç aylar.',
    'Her günümüz şükür, her gecemiz dua olsun. Allah gönlünüzdeki hayırlı niyetleri gerçek kılsın.',
    'Üç aylar, ruhun ekim mevsimidir. Ne ekerseniz Ramazan\'da onu biçersiniz; hayır ekin, bereket biçin.',
    'Manevi bir bahar kapıda… Kalbiniz yeşersin, dualarınız çiçek açsın, gönlünüz rahmetle sulansın. Hayırlı üç aylar.',
    'Bu mübarek mevsimde tövbeleriniz kabul, ibadetleriniz makbul, gönlünüz nurla dolu olsun.',
    'Receb Allah\'ın, Şaban Peygamber\'in, Ramazan ümmetin ayıdır derler. Bu bereketli yolculuk size hayır getirsin.',
    'Üç ayların rahmet iklimi gönlünüzü ısıtsın, uzakları yakın, kırgınları dost etsin. Hayırlı üç aylar.',
  ]),
];
